### PR TITLE
fix TLS cert bug

### LINKED ISSUE #3000: [Bug] When accessing the Flink address on flink on k8s, if ingress is configured, the https address becomes inaccessible.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.1

### Flink Version

1.14.5

### deploy mode

kubernetes-application

### What happened

When the ingress controller address is configured, the ingress created by the submitted job does not have certificate configuration, and TLS protocol info appears in the logs. So changing https to http can fix it.

### Error Exception

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by chenshaojin**
## What changes were proposed in this pull request

Issue Number: close #3000

### CODE REVIEW

**Comment by chenshaojin** [comment]
cc @Al-assad

**Review by Al-assad — APPROVED** [review]
LGTM

**Comment by Al-assad** [comment]
cc @wolfboys

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
