### PR TITLE
[Bug] Fix update state failed when using h2 db.

### PR DESCRIPTION
**Pull request by lvshaokang**
Problem Summary: Fix update state failed when using h2 db.

### What is changed and how it works?

Proposal: [xxx](url) 

Feel free to ping committers for the review!

## Contribution Checklist

  - Make sure that the pull request corresponds to a [GITHUB issue](https://github.com/streamxhub/streamx/issues).

  - Name the pull request in the form "[Feature] [component] Title of the pull request", where *Feature* can be replaced by `Hotfix`, `Bug`, etc.

  - Minor fixes should be named following this pattern: `[hotfix] [docs] Fix typo in README.md doc`.

### CODE REVIEW

**Comment by lvshaokang** [comment]
When using h2 db, in the `baseMapper.update`, entity and updateWrapper use duplicate columns, caused update state failed.
@wolfboys PTAL.

**Comment by lvshaokang** [comment]
@VampireAchao Here is the error log under h2 db.
```
[streamx-build-pipeline-executor-0] INFO com.streamxhub.streamx.console.core.entity.Application - remote appHome:hdfs://106.52.120.187:9000/streamx/workspace/100001
org.springframework.jdbc.BadSqlGrammarException: 
### Error updating database.  Cause: org.h2.jdbc.JdbcSQLSyntaxErrorException: Duplicate column name "launch"; SQL statement:
UPDATE t_flink_app  SET job_type=?,

user_id=?,
team_id=?,
job_name=?,
app_id=?,
job_id=?,
version_id=?,


k8s_namespace=?,
state=?,
launch=?,
build=?,
restart_size=?,

option_state=?,

args=?,

options=?,

resolve_order=?,
execution_mode=?,

app_type=?,
flame_graph=?,
tracking=?,
jar=?,
jar_check_sum=?,
main_class=?,

end_time=?,












create_time=?,

modify_time=?,






resource_from=?,
k8s_hadoop_integration=?,

launch=?,build=?,option_state=?  
 
 WHERE (id = ?) [42121-214]
### The error may exist in com/streamxhub/streamx/console/core/mapper/ApplicationMapper.java (best guess)
### The error may involve com.streamxhub.streamx.console.core.mapper.ApplicationMapper.update
### The error occurred while executing an update
### SQL: UPDATE t_flink_app  SET job_type=?,  user_id=?, team_id=?, job_name=?, app_id=?, job_id=?, version_id=?,   k8s_namespace=?, state=?, launch=?, build=?, restart_size=?,  option_state=?,  args=?,  options=?,  resolve_order=?, execution_mode=?,  app_type=?, flame_graph=?, tracking=?, jar=?, jar_check_sum=?, main_class=?,  end_time=?,             create_time=?,  modify_time=?,       resource_from=?, k8s_hadoop_integration=?,  launch=?,build=?,option_state=?      WHERE (id = ?)
### Cause: org.h2.jdbc.JdbcSQLSyntaxErrorException: Duplicate column name "launch"; SQL statement:
UPDATE t_flink_app  SET job_type=?,

user_id=?,
team_id=?,
job_name=?,
app_id=?,
job_id=?,
version_id=?,


k8s_namespace=?,
state=?,
launch=?,
build=?,
restart_size=?,

option_state=?,

args=?,

options=?,

resolve_order=?,
execution_mode=?,

app_type=?,
flame_graph=?,
tracking=?,
jar=?,
jar_check_sum=?,
main_class=?,

end_time=?,












create_time=?,

modify_time=?,






resource_from=?,
k8s_hadoop_integration=?,

launch=?,build=?,option_state=?  
 
 WHERE (id = ?) [42121-214]
; bad SQL grammar []; nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Duplicate column name "launch"; SQL statement:
UPDATE t_flink_app  SET job_type=?,

user_id=?,
team_id=?,
job_name=?,
app_id=?,
job_id=?,
version_id=?,


k8s_namespace=?,
state=?,
launch=?,
build=?,
restart_size=?,

option_state=?,

args=?,

options=?,

resolve_order=?,
execution_mode=?,

app_type=?,
flame_graph=?,
tracking=?,
jar=?,
jar_check_sum=?,
main_class=?,

end_time=?,












create_time=?,

modify_time=?,






resource_from=?,
k8s_hadoop_integration=?,

launch=?,build=?,option_state=?  
 
 WHERE (id = ?) [42121-214]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy113.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:288)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:64)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy130.update(Unknown Source)
	at com.streamxhub.streamx.console.core.service.impl.ApplicationServiceImpl.updateLaunch(ApplicationServiceImpl.java:871)
	at com.streamxhub.streamx.console.core.service.impl.ApplicationServiceImpl$$FastClassBySpringCGLIB$$4cca1efc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at com.streamxhub.streamx.console.core.aspect.StreamXConsoleAspect.lambda$refreshCache$0(StreamXConsoleAspect.java:60)
	at com.streamxhub.streamx.console.core.task.FlinkTrackingTask.refreshTracking(FlinkTrackingTask.java:626)
	at com.streamxhub.streamx.console.core.aspect.StreamXConsoleAspect.refreshCache(StreamXConsoleAspect.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.streamxhub.streamx.console.core.service.impl.ApplicationServiceImpl$$EnhancerBySpringCGLIB$$1f80102d.updateLaunch(<generated>)
	at com.streamxhub.streamx.console.core.service.impl.ApplBuildPipeServiceImpl$1.onFinish(ApplBuildPipeServiceImpl.java:275)
	at com.streamxhub.streamx.flink.packer.pipeline.BuildPipeline.launch(BuildPipeline.scala:169)
	at com.streamxhub.streamx.flink.packer.pipeline.BuildPipeline.launch$(BuildPipeline.scala:157)
	at com.streamxhub.streamx.flink.packer.pipeline.impl.FlinkYarnApplicationBuildPipeline.launch(FlinkYarnApplicationBuildPipeline.scala:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by VampireAchao** [comment]
Thank U :trollface:

**Comment by lvshaokang** [comment]
Follow https://github.com/streamxhub/streampark/pull/1493
closed

**Pull request closed without merging**
