### PR TITLE
[Issue-2513][Polish] Delete tutorial backend code.

### LINKED ISSUE #2513: [Polish] Delete tutorial backend code.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

_No response_

### Scala Version

2.11.x

### StreamPark Version

latest

### Flink Version

none

### deploy mode

None

### What happened

企业微信截图_16799887702560
`tutorial` was useless and should be deleted.

### Error Exception

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Kick156**
## What changes were proposed in this pull request

Issue Number: close #2513 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / **no**)

### CODE REVIEW

**Review by wolfboys — COMMENTED** [review]
fe related files also need to be cleaned up:  notebook.ts etc

**Comment by Kick156** [comment]
the notebook.ts involve Submit.less，Submit.vue  in views/flink/notebook，I also clean them up，is that right？

**Review by wolfboys — COMMENTED** [review]
The changed sql needs to be added in the [upgrade sql script](https://github.com/apache/incubator-streampark/tree/dev/streampark-console/streampark-console-service/src/main/assembly/script/upgrade)

**Comment by wolfboys** [comment]
cc @wangsizhu0504 PTAL

**Review by wangsizhu0504 — APPROVED** [review]
LGTM!

**Pull request merged**
