### PR TITLE
[Improve] workspace local permission check

### PR DESCRIPTION
**Pull request by wolfboys**
[Improve] workspace local permission check

### CODE REVIEW

**Comment by wolfboys** [comment]
cc @tisonkun PTAL, thx

**Review by tisonkun — COMMENTED** [review]
Is it possible we just change the default value to a folder under current working dir? For example, `workspace.local` = `./streampark_workspace` or just `./workspace`.

**Comment by wolfboys** [comment]
> Is it possible we just change the default value to a folder under current working dir? For example, `workspace.local` = `./streampark_workspace` or just `./workspace`.


ok, It's a good idea!. If we do it in this way, We need to mkdir "workspace" under $APP_HOME, and the program need to recognize the `./` path

**Comment by tisonkun** [comment]
```diff
commit ac85eb42fa8334f294a59a511585b0fc4a9f97d7 (HEAD -> workspace)
Author: tison <wander4096@gmail.com>
Date:   Thu Apr 13 09:00:46 2023 +0800

    local dir = workspace
    
    Signed-off-by: tison <wander4096@gmail.com>

diff --git a/deploy/helm/streampark/conf/streampark-console-config/application.yml b/deploy/helm/streampark/conf/streampark-console-config/application.yml
index 422fd0ae3..714636563 100755
--- a/deploy/helm/streampark/conf/streampark-console-config/application.yml
+++ b/deploy/helm/streampark/conf/streampark-console-config/application.yml
@@ -83,7 +83,7 @@ streampark:
   hadoop-user-name: hdfs
   # local workspace, used to store source code and build dir etc.
   workspace:
-    local: /opt/streampark_workspace
+    local: workspace
     remote: hdfs://hdfscluster/streampark   # support hdfs:///streampark/ 、 /streampark 、hdfs://host:ip/streampark/
 
   # remote docker register namespace for streampark
```

I guess it's as simple as the patch above. Perhaps you should ensure `streampark.sh` `cd` to `$APP_HOME`. Always the path is resolved against current directory.

**Comment by wolfboys** [comment]
> Is it possible we just change the default value to a folder under current working dir? For example, `workspace.local` = `./streampark_workspace` or just `./workspace`.

Thanks for your review, it is not recommended to defined `workspace` directory under the project(`$APP_HOME/workspace`), because users will upload jars to this workspace directory. If the streampark upgraded or redeployed, this path will change, which will lead to The dependency jars in many jobs in the user's historical jobs cannot find the path. Therefore, this path needs to be configured separately. Configured to a safe directory

**Review by muchunjin — APPROVED** [review]
LGTM

**Pull request merged**
