### PR TITLE
[FIX] fix teamId is null occur an sql error

### LINKED ISSUE #3361: [Bug] findUserPermissions SQL execute bug
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.2

### Flink Version

all

### deploy mode

kubernetes-application

### What happened

After the user login web, the user web Aaert SQL executes an error

### Error Exception

_No response_

### Screenshots

image

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by minchowang**
## What changes were proposed in this pull request

Issue Number: close #3361 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Comment by caicancai** [comment]
Thank you for your contribution

**Review by wolfboys — APPROVED** [review]
LGTM, Thanks  for your contribution, Looking forward to your next contribution。

**Comment by wolfboys** [comment]
cc @minchowang The RC branch is a release candidate, It is not recommended to commit to this branch, Can you commit the code to the dev-2.1.2  branch?

**Review by caicancai — APPROVED** [review]

**Comment by minchowang** [comment]
> cc @minchowang The RC branch is a release candidate, It is not recommended to commit to this branch, Can you commit the code to the dev-2.1.2 branch?

OK, this pr https://github.com/apache/incubator-streampark/pull/3365

**Comment by wolfboys** [comment]
> > cc @minchowang The RC branch is a release candidate, It is not recommended to commit to this branch, Can you commit the code to the dev-2.1.2 branch?
> 
> OK, this pr #3365

Thanks, Great job! The issue also exists in the dev branch. Can you please submit it to the dev branch again? 👍

**Pull request closed without merging**
