### PR TITLE
[Issue-2324][Feature] Add SQL DDL & DML for Yarn queue management feature.

### LINKED ISSUE #2324: [Feature] Introduce yarn queue setting to manage the queue resouce
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

# Intention

Maybe we could introduce the queue-resource-manage feature. There will be  some advantage:
- Keeping the available yarn-queues in `streampark` is helpful to keep the boundary between `Streampark` and `yarn-cluster`.
  - Prevent queue abuse.
  - Prevent failed submission caused by non-existent queue.
- Make it easier for users to perceive and to user the available yarn queues.
  - Support select queue when users using the  `yarn-application` & `yarn-session` mode to deploy the jobs.

# What 
- The expected outline  of the yarn queue management

image
image

- Support select queue when deploying on yarn.

deploy yarn session  
image

deploy yarn-application jobs  
image

# How

- Introduce the yarn queue table to store the queue info
fields:  
  - id
  - team_id
  - queue_label
  - description
  - create_time
  - modify_time
unique key `unq_team_id_queue_label` (`team_id`, `queue_label`)

- Need to note: Check the queue references( by yarn-session clusters & yarn-application jobs) when delete yarn queue.

### SubTasks
- [x] Completed #2415 
- [x] Completed #2416 
- [x] Completed #2418 
- [x] Completed #2420 
- [x]  Completed #2470

### Usage Scenario

_No response_

### Related issues

#2299 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by RocMarshal**
## What changes were proposed in this pull request

Issue Number: close #2324

## Brief change log

Add SQL statements and default backend implementation for YarnQueue management

## Verifying this change

- *Manually verified the change by testing locally.* 

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / **no**)

### CODE REVIEW

**Comment by RocMarshal** [comment]
hi, @wolfboys . Could you help to review this if you are in free time ? thank you.

**Comment by wolfboys** [comment]
> hi, @wolfboys . Could you help to review this if you are in free time ? thank you.

Thanks for your contribution, I will review it later.

**Comment by wolfboys** [comment]
Great feature, unified management of the use of yarn-queue👍  How to be compatible with historical jobs is a problem we have to solve.We have discussed this issue offline, but it is still inconclusive and needs further discussion

**Comment by RocMarshal** [comment]
> Great feature, unified management of the use of yarn-queue👍 How to be compatible with historical jobs is a problem we have to solve.We have discussed this issue offline, but it is still inconclusive and needs further discussion

The new discussion result was recorded in the corresponding issue.

**Comment by RocMarshal** [comment]
Migrated into https://github.com/apache/incubator-streampark/pull/2419

**Pull request closed without merging**
