### PR TITLE
[improve] add more debug log

### PR DESCRIPTION
**Pull request by Mrart**
## What changes were proposed in this pull request

Issue Number: close #xxx 

## Brief change log

add more debug log
## Verifying this change

This change is already covered by existing tests, such as *(please describe tests)*.
no

This change added tests and can be verified as follows:
[improve] add more debug log

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (no)

### CODE REVIEW

**Review by wolfboys — APPROVED** [review]
LGTM

**Comment by caicancai** [comment]
@wolfboys I don’t know why the code now mentions the release branch, 2.1.5 instead of the dev branch. I don’t know if this is the right decision, but in my opinion it is unreasonable.
I remember I expressed my concern a long time ago that when there are more and more branches and the differences between them and the dev branch become larger and larger, it will be difficult to maintain.

**Comment by wolfboys** [comment]
> @wolfboys I don’t know why the code now mentions the release branch, 2.1.5 instead of the dev branch. I don’t know if this is the right decision, but in my opinion it is unreasonable. I remember I expressed my concern a long time ago that when there are more and more branches and the differences between them and the dev branch become larger and larger, it will be difficult to maintain.

2.1.5 only accepts bug fixes and improvements, and does not introduce new features. Currently, the official release version of StreamPark is still the 2.1. x. Therefore, before the official release of version 2.2, bugs and PRs reported by users will be accepted.  Updating multiple branches is normal development work. Many projects maintain multiple branches at the same time, such as Apache Flink..

**Comment by caicancai** [comment]
@Mrart Can you submit another pr to dev?

**Pull request merged**
