### PR TITLE
[Bug] Rename the teamId of user table to lastTeamId

### LINKED ISSUE #2030: [Bug] When the user logs in, it prompts that there is no permission
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When creating a user, the user's team_id in the t_user table is filled with the current team, but other teams are selected when assigning roles. At this time, the user will be prompted to log in without permission. 

The specific operation steps are as follows:
1. Create an account `test` in `team A`
2. Switch to `team B` and add a developer role to the `test` account
3. Use the `test` account to log in, at this time it prompts no permission

### StreamPark Version

2.0.0

### Java Version

_No response_

### Flink Version

1.14.3

### Scala Version of Flink

2.12

### Error Exception

```log
Prompt no permission
```

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by 1996fanrui**
## What changes were proposed in this pull request

Issue Number: close #2030 

Avoid the bug that the lastTeamId of new user isn't null

## Brief change log

Rename the teamId of user table to lastTeamId

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): no

### CODE REVIEW

**Comment by 1996fanrui** [comment]
Hi @wolfboys @macksonmu , I have tested #2030 in my development env, it is fixed. 

Please help review in your free time, thanks~

And please  @wangsizhu0504 help to check whether the front-end modification is missing, thanks a lot~

**Review by wangsizhu0504 — COMMENTED** [review]
LGTM! Very Good.

**Comment by macksonmu** [comment]
LGTM

**Review by muchunjin — COMMENTED** [review]
LGTM

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
