### PR TITLE
[Improve] update mapper Boolean return type to primitive

### PR DESCRIPTION
**Pull request by VampireAchao**
## What changes were proposed in this pull request

**Modify mapper function return type Boolean to boolean**

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Review by wuchunfu — APPROVED** [review]
LGTM

**Comment by caicancai** [comment]
@VampireAchao Hi, thank you for your contribution, can I please tell you why this change is made, it is conducive to archiving

**Comment by VampireAchao** [comment]
> @VampireAchao Hi, thank you for your contribution, can I please tell you why this change is made, it is conducive to archiving您好，感谢您的贡献，请您告诉您为什么进行此更改，这有利于存档

1. "The return type of the Boolean method in the mybatis mapper will not be null."
2. "Refer to: [SonarSource Java Rule RSPEC-5411](https://rules.sonarsource.com/java/RSPEC-5411/)."

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
