### PR TITLE
[Bug] fix yarn session address config loss

### PR DESCRIPTION
**Pull request by msftgitsklsd**
## Purpose of this pull request

Sloved address lossing problem when edits config

### CODE REVIEW

**Comment by wolfboys** [comment]
@xxyykkxx  PTAL

**Review by xxyykkxx — CHANGES_REQUESTED** [review]
the executionMode in cluster mode is (1:remode,3:yarn-session,5:k8s-session),
wanna display the address just change
 &lt;template v-else&gt; TO &lt;template v-if="executionMode === 3 || executionMode === 5"&gt;

**Comment by msftgitsklsd** [comment]
> the executionMode in cluster mode is (1:remode,3:yarn-session,5:k8s-session), wanna display the address just change <template v-else> TO <template v-if="executionMode === 3 || executionMode === 5">

already changed

**Review by xxyykkxx — APPROVED** [review]
LGTM

**Comment by wolfboys** [comment]
LGTM

**Pull request merged**
