### PR TITLE
[Feature] Split each version of sql-upgrade.sql into a different directory

### LINKED ISSUE #1687: [Feature] Split each version of sql-upgrade.sql into a different directory
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Split each version of sql-upgrade.sql into a different directory

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by 1996fanrui**
## What problem does this PR solve?

Issue Number: close #1687 

Problem Summary:

Split each version of sql-upgrade.sql into a different directory

## What is changed and how it works?

Proposal: [xxx](url) 

Feel free to ping committers for the review!

## Contribution Checklist

  - Make sure that the pull request corresponds to a [GITHUB issue](https://github.com/apache/streampark/issues).

  - Name the pull request in the form "[Feature] [component] Title of the pull request", where *Feature* can be replaced by `Hotfix`, `Bug`, etc.

  - Minor fixes should be named following this pattern: `[hotfix] [docs] Fix typo in README.md doc`.

## Purpose of this pull request

Split each version of sql-upgrade.sql into a different directory

### CODE REVIEW

**Comment by xinzhuxiansheng** [comment]
@1996fanrui @wolfboys  Do we need to split sql into DDL, DML?

**Comment by wolfboys** [comment]
I have seen other apache projects about script directory structure , have a preliminary idea:

```
.
script
├── schema
│    ├── mysql-schema.sql
│    ├── pgsql-schema.sql
├── data
│    ├── mysql-data.sql
│    ├── pgsql-data.sql
├── upgrade
│    ├── mysql-1.0.0.sql
│    ├── mysql-1.1.0-up-1.1.1.sql
│    ├── mysql-1.1.1-up-1.1.2.sql
│    ├── mysql-1.1.2-up-1.1.3.sql
│    ├── pgsql-1.0.0.sql
│    ├── pgsql-1.1.0-up-1.1.1.sql
│    ├── pgsql-1.1.1-up-1.1.2.sql
│    ├── pgsql-1.1.2-up-1.1.3.sql
│    ├── ...
│    ├── readme.md

```

What do you think of this directory structure? Please feedback your opinions and discuss together

**Comment by 1996fanrui** [comment]
> @1996fanrui @wolfboys Do we need to split sql into DDL, DML?

Hi @xinzhuxiansheng thanks for your review. Discussed with @wolfboys , we decided to merge dml and ddl into one file for two reasons:

1. It's convenient for user to execute them.
2. Splitting into two files may have bugs in some scenarios. E.g:
- Create B-table (DDL)
- Migrate table A data to new table B (DML)
- Delete the obsolete fields of A table (DDL)

That's, scenarios where DML is executed between multiple DDLs may have bugs.

**Comment by 1996fanrui** [comment]
> I have seen other apache projects about script directory structure , have a preliminary idea:
> 
> ```
> .
> script
> ├── schema
> │    ├── mysql-schema.sql
> │    ├── pgsql-schema.sql
> ├── data
> │    ├── mysql-data.sql
> │    ├── pgsql-data.sql
> ├── upgrade
> │    ├── mysql-1.0.0.sql
> │    ├── mysql-1.1.0-up-1.1.1.sql
> │    ├── mysql-1.1.1-up-1.1.2.sql
> │    ├── mysql-1.1.2-up-1.1.3.sql
> │    ├── pgsql-1.0.0.sql
> │    ├── pgsql-1.1.0-up-1.1.1.sql
> │    ├── pgsql-1.1.1-up-1.1.2.sql
> │    ├── pgsql-1.1.2-up-1.1.3.sql
> │    ├── ...
> │    ├── readme.md
> ```
> 
> What do you think of this directory structure? Please feedback your opinions and discuss together

Hi @wolfboys , thanks for you suggestions.

I have some concerns:

1. The old version of `mysql-1.0.0.sql` should not be necessary. If the old version is used, the user can switch to the corresponding tag to find the complete schema and data sql at that time. Or why do we need the `mysql-1.0.0.sql`? Very few users use this version.
2. All streampark versions and files for multiple databases are mixed in one directory, is it clear?
3. Is `db-1.1.3.sql` enough? upgrade means: the previous version to the current version. The new name is `db-1.1.2-up-1.1.3.sql` which is a bit redundant.
4. The `readme.md` is a good idea, it tells the user which sql file to execute during upgrade.

Actually, I prefer just add `readme.md` to this PR, what do you think?

**Comment by wolfboys** [comment]
> > I have seen other apache projects about script directory structure , have a preliminary idea:
> > ```
> > .
> > script
> > ├── schema
> > │    ├── mysql-schema.sql
> > │    ├── pgsql-schema.sql
> > ├── data
> > │    ├── mysql-data.sql
> > │    ├── pgsql-data.sql
> > ├── upgrade
> > │    ├── mysql-1.0.0.sql
> > │    ├── mysql-1.1.0-up-1.1.1.sql
> > │    ├── mysql-1.1.1-up-1.1.2.sql
> > │    ├── mysql-1.1.2-up-1.1.3.sql
> > │    ├── pgsql-1.0.0.sql
> > │    ├── pgsql-1.1.0-up-1.1.1.sql
> > │    ├── pgsql-1.1.1-up-1.1.2.sql
> > │    ├── pgsql-1.1.2-up-1.1.3.sql
> > │    ├── ...
> > │    ├── readme.md
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What do you think of this directory structure? Please feedback your opinions and discuss together
> 
> Hi @wolfboys , thanks for you suggestions.
> 
> I have some concerns:
> 
> 1. The old version of `mysql-1.0.0.sql` should not be necessary. If the old version is used, the user can switch to the corresponding tag to find the complete schema and data sql at that time. Or why do we need the `mysql-1.0.0.sql`? Very few users use this version.
> 2. All streampark versions and files for multiple databases are mixed in one directory, is it clear?
> 3. Is `db-1.1.3.sql` enough? upgrade means: the previous version to the current version. The new name is `db-1.1.2-up-1.1.3.sql` which is a bit redundant.
> 4. The `readme.md` is a good idea, it tells the user which sql file to execute during upgrade.
> 
> Actually, I prefer just add `readme.md` to this PR, what do you think?

Hi @1996fanrui  , thanks for you suggestions. 

1. "The old version of mysql-1.0.0.sql should not be necessary", I agree with you, it's really not necessary
2. "All streampark versions and files for multiple databases are mixed in one directory, is it clear?", It's really not clear.

how about this:

```
.
script
├── schema
│    ├── mysql-schema.sql
│    ├── pgsql-schema.sql
├── data
│    ├── mysql-data.sql
│    ├── pgsql-data.sql
├── upgrade
│    ├── mysql
│    │     ├── 1.1.0-up-1.1.1.sql
│    │     ├── 1.1.1-up-1.1.2.sql
│    │     ├── 1.1.2-up-1.1.3.sql
│    │     ├── ...
│    ├── pgsql
│    │     ├── 1.1.0-up-1.1.1.sql
│    │     ├── 1.1.1-up-1.1.2.sql
│    │     ├── 1.1.2-up-1.1.3.sql
│    │     ├── ...
│   readme.md

```

**Comment by 1996fanrui** [comment]
> Hi @1996fanrui , thanks for you suggestions.
> 
>     1. "The old version of mysql-1.0.0.sql should not be necessary", I agree with you, it's really not necessary
> 
>     2. "All streampark versions and files for multiple databases are mixed in one directory, is it clear?", It's really not clear.
> 
> 
> how about this:
> 
> ```
> .
> script
> ├── schema
> │    ├── mysql-schema.sql
> │    ├── pgsql-schema.sql
> ├── data
> │    ├── mysql-data.sql
> │    ├── pgsql-data.sql
> ├── upgrade
> │    ├── mysql
> │    │     ├── 1.1.0-up-1.1.1.sql
> │    │     ├── 1.1.1-up-1.1.2.sql
> │    │     ├── 1.1.2-up-1.1.3.sql
> │    │     ├── ...
> │    ├── pgsql
> │    │     ├── 1.1.0-up-1.1.1.sql
> │    │     ├── 1.1.1-up-1.1.2.sql
> │    │     ├── 1.1.2-up-1.1.3.sql
> │    │     ├── ...
> │   readme.md
> ```

upgrade means: the previous version to the current version. The new name is `1.1.2-up-1.1.3.sql `which is a bit redundant, so I think `1.1.3.sql` is enough, what do you think?

like this:


> ```
> .
> script
> ├── schema
> │    ├── mysql-schema.sql
> │    ├── pgsql-schema.sql
> ├── data
> │    ├── mysql-data.sql
> │    ├── pgsql-data.sql
> ├── upgrade
> │    ├── mysql
> │    │     ├── 1.1.1.sql
> │    │     ├── 1.1.2.sql
> │    │     ├── 1.1.3.sql
> │    │     ├── ...
> │    ├── pgsql
> │    │     ├── 1.1.1.sql
> │    │     ├── 1.1.2.sql
> │    │     ├── 1.1.3.sql
> │    │     ├── ...
> │   readme.md
> ```

**Comment by wolfboys** [comment]
> 1. I agree with you



> > Hi @1996fanrui , thanks for you suggestions.
> > ```
> > 1. "The old version of mysql-1.0.0.sql should not be necessary", I agree with you, it's really not necessary
> > 
> > 2. "All streampark versions and files for multiple databases are mixed in one directory, is it clear?", It's really not clear.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > how about this:
> > ```
> > .
> > script
> > ├── schema
> > │    ├── mysql-schema.sql
> > │    ├── pgsql-schema.sql
> > ├── data
> > │    ├── mysql-data.sql
> > │    ├── pgsql-data.sql
> > ├── upgrade
> > │    ├── mysql
> > │    │     ├── 1.1.0-up-1.1.1.sql
> > │    │     ├── 1.1.1-up-1.1.2.sql
> > │    │     ├── 1.1.2-up-1.1.3.sql
> > │    │     ├── ...
> > │    ├── pgsql
> > │    │     ├── 1.1.0-up-1.1.1.sql
> > │    │     ├── 1.1.1-up-1.1.2.sql
> > │    │     ├── 1.1.2-up-1.1.3.sql
> > │    │     ├── ...
> > │   readme.md
> > ```
> 
> upgrade means: the previous version to the current version. The new name is `1.1.2-up-1.1.3.sql `which is a bit redundant, so I think `1.1.3.sql` is enough, what do you think?
> 
> like this:
> 
> > ```
> > .
> > script
> > ├── schema
> > │    ├── mysql-schema.sql
> > │    ├── pgsql-schema.sql
> > ├── data
> > │    ├── mysql-data.sql
> > │    ├── pgsql-data.sql
> > ├── upgrade
> > │    ├── mysql
> > │    │     ├── 1.1.1.sql
> > │    │     ├── 1.1.2.sql
> > │    │     ├── 1.1.3.sql
> > │    │     ├── ...
> > │    ├── pgsql
> > │    │     ├── 1.1.1.sql
> > │    │     ├── 1.1.2.sql
> > │    │     ├── 1.1.3.sql
> > │    │     ├── ...
> > │   readme.md
> > ```

looks good.  I agree with you.

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
