### PR TITLE
flink 国内下载慢 改成腾讯镜像

### PR DESCRIPTION
**Pull request by happyi**
flink 国内下载慢 改成腾讯镜像

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

Feel free to ping committers for the review!

## Contribution Checklist

  - Make sure that the pull request corresponds to a [GITHUB issue](https://github.com/streamxhub/streamx/issues).

  - Name the pull request in the form "[Feature] [component] Title of the pull request", where *Feature* can be replaced by `Hotfix`, `Bug`, etc.

  - Minor fixes should be named following this pattern: `[hotfix] [docs] Fix typo in README.md doc`.

-->

## Purpose of this pull request

修改后的效果
297150K .......... .......... .......... .......... .......... 99% 1.05M 0s
297200K .......... .......... .......... .......... .......... 99% 9.25M 0s
297250K .......... .......... .......... .......... .......... 99% 11.0M 0s
297300K .......... .......... .......... .......... .......... 99% 1.21M 0s
297350K .......... .......... .......... .......... .......... 99% 11.3M 0s
297400K .......... .......... .......... .......... .......... 99% 9.71M 0s
297450K .......... .......... .......... .......... .......... 99% 10.7M 0s
297500K .......... .......... .......... .......... .......... 99% 1.10M 0s
297550K .........                                             100% 67.5M=3m26s

修改之前
 1150K .......... .......... .......... .......... ..........  0% 57.5K 94m35s
  1200K .......... .......... .......... .......... ..........  0% 94.4K 92m52s
  1250K .......... .......... .......... .......... ..........  0% 83.3K 91m34s
  1300K .......... .......... .......... .......... ..........  0% 69.0K 90m49s
  1350K .......... .......... .......... .......... ..........  0% 71.1K 90m2s
  1400K .......... .......... .......... .......... ..........  0% 83.0K 88m58s
  1450K .......... .......... .......... .......... ..........  0% 77.6K 88m6s
  1500K .......... .......... .......... .......... ..........  0% 85.8K 87m6s
  1550K .......... .......... .......... .......... ..........  0% 32.8K 89m4s
  1600K .......... .......... .......... .......... ..........  0% 36.0K 90m30s
  1650K .......... .......... .......... .......... ..........  0% 62.0K 90m10s

### CODE REVIEW

**Comment by wolfboys** [comment]
@MonsterChenzhuo PTAL

**Comment by MonsterChenzhuo** [comment]
LGTM

**Comment by wolfboys** [comment]
LGTM

**Comment by wolfboys** [comment]
LGTM

**Pull request merged**
