### PR TITLE
[Feature] Optimize log printing and return in GlobalExceptionHandler

### LINKED ISSUE #3704: [Feature] Optimize log printing and return in GlobalExceptionHandler
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Optimize log printing and return in GlobalExceptionHandler

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Mrart**
## What changes were proposed in this pull request

Issue Number: close #3704 
Optimize log printing and return in GlobalExceptionHandler

## Brief change log

Optimize log printing and return in GlobalExceptionHandler
## Verifying this change

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)* yes

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes )

### CODE REVIEW

**Comment by caicancai** [comment]
@Mrart  Can you resolve conflicts?

**Comment by caicancai** [comment]
The changes look good, I can merge them if the conflicts are resolved

**Comment by Mrart** [comment]
> The changes look good, I can merge them if the conflicts are resolved

improve

**Review by caicancai — APPROVED** [review]
LGTM

**Pull request merged**
