### PR TITLE
[Improve] login page style Improvement

### PR DESCRIPTION
**Pull request by wolfboys**
[Improve] login page style Improvement

## What changes were proposed in this pull request

image

### CODE REVIEW

**Review by wangsizhu0504 — COMMENTED** [review]
It looks good! However, the left and right padding of the login box can be appropriately increased. Is it better?

**Comment by wolfboys** [comment]
> It looks good! However, the left and right padding of the login box can be appropriately increased. Is it better?

I'm working on this

**Comment by wolfboys** [comment]
> It looks good! However, the left and right padding of the login box can be appropriately increased. Is it better?

done

**Review by wangsizhu0504 — COMMENTED** [review]
LGTM

**Review by wangsizhu0504 — APPROVED** [review]
LGTM

**Pull request merged**
