### PR TITLE
[Improve] maven build args improvement

### PR DESCRIPTION
**Pull request by wolfboys**
[Improve] maven build args improvement

### CODE REVIEW

**Comment by caicancai** [comment]
cc @wangsizhu0504 Excuse me, if you have time, can you help me review it?

**Review by wangsizhu0504 — DISMISSED** [review]
Frontend LGTM!

**Comment by wangsizhu0504** [comment]
> it?

I checked the frontend part and found no problem

**Review by GOODBOY008 — APPROVED** [review]
LGTM

**Pull request merged**
