### PR TITLE
[Improve]: update FE dependencies, use pnpm

### PR DESCRIPTION
**Pull request by wangsizhu0504**
## What changes were proposed in this pull request

Issue Number: close #xxx 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes)

- Upgrade front-end dependencies to latest, test compilation deployment(Except for the sql-formatter dependency)

- eslint code 

Post-Deployment Interface

image

### CODE REVIEW

**Comment by wangsizhu0504** [comment]
@wolfboys The front-end dependency upgrade is complete, help test if there are any problems after the overall compilation and deployment

**Comment by wolfboys** [comment]
cc @onlyotdn If you have free time, please test this PR

**Review by wolfboys — APPROVED** [review]
LGTM

**Comment by onlyotdn** [comment]
@wangsizhu0504  When executing the ./build.sh script, the following error occurred:
```
[INFO] --- frontend-maven-plugin:1.12.1:pnpm (build) @ streampark-console-service ---
[INFO] Running 'pnpm run build:no-cache' in /Users/bytedance/IdeaProjects/incubator-streampark/streampark-console/streampark-console-service/../streampark-console-webapp
[INFO] 
[INFO] > streampark-webapp@2.2.0-SNAPSHOT build:no-cache /Users/bytedance/IdeaProjects/incubator-streampark/streampark-console/streampark-console-webapp
[INFO] > npm run clean:cache && npm run build
[INFO] 
[INFO] 
[INFO] > streampark-webapp@2.2.0-SNAPSHOT clean:cache
[INFO] > rimraf node_modules/.cache/ && rimraf node_modules/.vite
[INFO] 
[INFO] 
[INFO] > streampark-webapp@2.2.0-SNAPSHOT build
[INFO] > cross-env NODE_ENV=production NODE_OPTIONS=--max-old-space-size=8192 pnpm vite build
[INFO] 
[INFO] node:events:505
[INFO]       throw er; // Unhandled 'error' event
[INFO]       ^
[INFO] 
[INFO] Error: spawn pnpm ENOENT
[INFO]     at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
[INFO]     at onErrorNT (node:internal/child_process:478:16)
[INFO]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[INFO] Emitted 'error' event on ChildProcess instance at:
[INFO]     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
[INFO]     at onErrorNT (node:internal/child_process:478:16)
[INFO]     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
[INFO]   errno: -2,
[INFO]   code: 'ENOENT',
[INFO]   syscall: 'spawn pnpm',
[INFO]   path: 'pnpm',
[INFO]   spawnargs: [ 'vite', 'build' ]
[INFO] }
[INFO]  ELIFECYCLE  Command failed with exit code 1.
[INFO] ------------------------------------------------------------------------
```

```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (build) on project streampark-console-service: Failed to run task: 'pnpm run build:no-cache' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :streampark-console-service
```

**Comment by wangsizhu0504** [comment]
> @wangsizhu0504 When executing the ./build.sh script, the following error occurred:
> 
> ```
> [INFO] --- frontend-maven-plugin:1.12.1:pnpm (build) @ streampark-console-service ---
> [INFO] Running 'pnpm run build:no-cache' in /Users/bytedance/IdeaProjects/incubator-streampark/streampark-console/streampark-console-service/../streampark-console-webapp
> [INFO] 
> [INFO] > streampark-webapp@2.2.0-SNAPSHOT build:no-cache /Users/bytedance/IdeaProjects/incubator-streampark/streampark-console/streampark-console-webapp
> [INFO] > npm run clean:cache && npm run build
> [INFO] 
> [INFO] 
> [INFO] > streampark-webapp@2.2.0-SNAPSHOT clean:cache
> [INFO] > rimraf node_modules/.cache/ && rimraf node_modules/.vite
> [INFO] 
> [INFO] 
> [INFO] > streampark-webapp@2.2.0-SNAPSHOT build
> [INFO] > cross-env NODE_ENV=production NODE_OPTIONS=--max-old-space-size=8192 pnpm vite build
> [INFO] 
> [INFO] node:events:505
> [INFO]       throw er; // Unhandled 'error' event
> [INFO]       ^
> [INFO] 
> [INFO] Error: spawn pnpm ENOENT
> [INFO]     at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
> [INFO]     at onErrorNT (node:internal/child_process:478:16)
> [INFO]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> [INFO] Emitted 'error' event on ChildProcess instance at:
> [INFO]     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
> [INFO]     at onErrorNT (node:internal/child_process:478:16)
> [INFO]     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
> [INFO]   errno: -2,
> [INFO]   code: 'ENOENT',
> [INFO]   syscall: 'spawn pnpm',
> [INFO]   path: 'pnpm',
> [INFO]   spawnargs: [ 'vite', 'build' ]
> [INFO] }
> [INFO]  ELIFECYCLE  Command failed with exit code 1.
> [INFO] ------------------------------------------------------------------------
> ```
> 
> ```
> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (build) on project streampark-console-service: Failed to run task: 'pnpm run build:no-cache' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :streampark-console-service
> ```

mac? Go to the streampark-console-webapp directory and run npm run build to try it out.

**Comment by onlyotdn** [comment]
> 

mac 

```
➜  streampark-console-webapp git:(dev) npm run build

> streampark-webapp@2.2.0-SNAPSHOT build
> cross-env NODE_ENV=production NODE_OPTIONS=--max-old-space-size=8192 pnpm vite build

node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn pnpm ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn pnpm',
  path: 'pnpm',
  spawnargs: [ 'vite', 'build' ]
}

Node.js v18.9.0

```

**Comment by wangsizhu0504** [comment]
> > 
> 
> mac
> 
> ```
> ➜  streampark-console-webapp git:(dev) npm run build
> 
> > streampark-webapp@2.2.0-SNAPSHOT build
> > cross-env NODE_ENV=production NODE_OPTIONS=--max-old-space-size=8192 pnpm vite build
> 
> node:events:491
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn pnpm ENOENT
>     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
>     at onErrorNT (node:internal/child_process:476:16)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> Emitted 'error' event on ChildProcess instance at:
>     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
>     at onErrorNT (node:internal/child_process:476:16)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'spawn pnpm',
>   path: 'pnpm',
>   spawnargs: [ 'vite', 'build' ]
> }
> 
> Node.js v18.9.0
> ```

Go to the webapp directory and edit the package.json file.

Modify the build command under scripts
```json 
"build": "vite build",
```
then run `npm run build`

**Comment by onlyotdn** [comment]
> > > 
> > 
> > 
> > mac
> > ```
> > ➜  streampark-console-webapp git:(dev) npm run build
> > 
> > > streampark-webapp@2.2.0-SNAPSHOT build
> > > cross-env NODE_ENV=production NODE_OPTIONS=--max-old-space-size=8192 pnpm vite build
> > 
> > node:events:491
> >       throw er; // Unhandled 'error' event
> >       ^
> > 
> > Error: spawn pnpm ENOENT
> >     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
> >     at onErrorNT (node:internal/child_process:476:16)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> > Emitted 'error' event on ChildProcess instance at:
> >     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
> >     at onErrorNT (node:internal/child_process:476:16)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
> >   errno: -2,
> >   code: 'ENOENT',
> >   syscall: 'spawn pnpm',
> >   path: 'pnpm',
> >   spawnargs: [ 'vite', 'build' ]
> > }
> > 
> > Node.js v18.9.0
> > ```
> 
> Go to the webapp directory and edit the package.json file.
> 
> Modify the build command under scripts
> 
> ```json
> "build": "vite build",
> ```
> 
> then run `npm run build`

It works , thanks.

**Pull request merged**
