### PR TITLE
remove 'mast have insert statement' limit

### PR DESCRIPTION
**Pull request by ziqiang-wang**
We don't mast write insert statement in flink sql job.
Each Flink SQL statement is executed immediately and individually, with corresponding effects.

### CODE REVIEW

**Comment by MonsterChenzhuo** [comment]
@ziqiang-wang 
Are you saying that pure create statements can be committed
select statements can also be committed

**Comment by ziqiang-wang** [comment]
1. The results of the SELECT statement cannot be collected locally, so the platform does not support the SELECT statement yet.
2. Each statement is executed immediately. For example, if the 'Create Hive Catalog' statement is written first and then the 'Create Table' statement is written, the metadata of the table will written to the Hive metadata.

**Comment by ziqiang-wang** [comment]
@MonsterChenzhuo 
The results of the SELECT statement cannot be collected locally, so the platform does not support the SELECT statement yet.
Each statement is executed immediately. For example, if the 'Create Hive Catalog' statement is written first and then the 'Create Table' statement is written, the metadata of the table will written to the Hive metadata.

**Comment by MonsterChenzhuo** [comment]
@ziqiang-wang He solved what pain point problem, I did not he understand his applicable scenario

**Comment by wolfboys** [comment]
The current version requires an insert operation so that the job can run

**Comment by ziqiang-wang** [comment]
This change was not necessary, I just discovered this feature.

For example, I created the Hive Catalog, and then only run some `create table` statement. Then other tasks do not need to write `create table` statement, and directly write an `INSERT` statement to run the job, which can reduce the redundancy of create table statements in job development.

**Pull request closed without merging**
