### PR TITLE
[Bug] branch authentication error bug fixed.(#1038)

### PR DESCRIPTION
**Pull request by rafaelxie**
1. fix branch authentication error bug , when a user first sign in the console web platform, update project in the /views/flink/project/Edit.vue component.

### CODE REVIEW

**Comment by wolfboys** [comment]
TBD , thank you very much for your contribution, is this change passed the test?

**Comment by rafaelxie** [comment]
yes, this change has passed the test.&nbsp;
By the way, I have two more questions :
1. Do you considering to support the ldap authentication function?
2. The table 't_flink_project' stores the user_name and password, but the password is stored in plaintext, maybe ciphertext storage is a better way. But in this scenario, when building a project, the fields of user_name and password are needed for github authentication, so maybe&nbsp;encryption algorithm is a better choice , not hashing algorithm.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "streamxhub/streamx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 凌晨0:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [streamxhub/streamx] [Bug] branch authentication error bug fixed.(#1038) (PR #1043)





 
TBD , thank you very much for your contribution, is this change passed the test?

**Comment by wolfboys** [comment]
LGTM.

**Comment by wolfboys** [comment]
> yes, this change has passed the test.&nbsp; By the way, I have two more questions : 1. Do you considering to support the ldap authentication function? 2. The table 't_flink_project' stores the user_name and password, but the password is stored in plaintext, maybe ciphertext storage is a better way. But in this scenario, when building a project, the fields of user_name and password are needed for github authentication, so maybe&nbsp;encryption algorithm is a better choice , not hashing algorithm.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "streamxhub/streamx" ***@***.***&gt;; 发送时间:&nbsp;2022年5月19日(星期四) 凌晨0:37 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [streamxhub/streamx] [Bug] branch authentication error bug fixed.(#1038) (PR #1043) TBD , thank you very much for your contribution, is this change passed the test? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

At present, the implementation is relatively simple. We look forward to improving this part.

**Pull request merged**
