### PR TITLE
[Feature] expose local mode in web-ui

### LINKED ISSUE #2444: [Feature] expose local mode in web-ui
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

This issue proposes to expose local mode which is already supported in the backend. For better experience, we should ensure the following features are available:
1.select local mode when editting job on the web-ui;
2.cancel local job;
3.close minicluster when job is done or terminated;
4.trigger savepoint for local job;
5.jump to Flink Web UI in detail tab;

### Usage Scenario

quick test for application

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhoulii**
## What changes were proposed in this pull request

Issue Number: close #2444 

## Verifying this change

Manually verified the change by testing locally, including:
_- select local mode when editting job on the web-ui;_
_- cancel local job;_
_- close minicluster when job is done or terminated;_
_- trigger savepoint for local job;_
_- jump to Flink Web UI in detail tab;_

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / **no**)

### CODE REVIEW

**Comment by wolfboys** [comment]
hi zhoulii:
Thanks for your contribution, local mode just a mini-cluster, Only for local testing, It is not difficult to support this function.  This mode cannot be used in production, If the user use this mode, it is likely to cause production accidents, If this feature is supported, it will bring confusion to users，so my side is -1

**Comment by zhoulii** [comment]
Hi @wolfboys ，Thanks for your explanation. I understand what's your concren, minicluster is really not suitable for production. But it provides a quick way to vertify your code. We can expose it and give some reminders, like [this](https://github.com/apache/incubator-streampark/pull/2445/files#diff-1af87e002f6aebaa77e25dc92317b1f7f588e36ecc3f1b1af776885114d82abfR113) , and give the choice to users.

**Comment by zhoulii** [comment]
Since this is not an urgent demand, I will close this pr and related issue one day later if no more comments received. We can reopen it if necessary, thanks again for the reply @wolfboys .

**Comment by wolfboys** [comment]
> Since this is not an urgent demand, I will close this pr and related issue one day later if no more comments received. We can reopen it if necessary, thanks again for the reply @wolfboys .

quick way to verify code and interactive query already in roadmap, we plan to integrate flinksql-gateway, see https://github.com/apache/incubator-streampark/issues/2274, your can send email to dev@streampark.apache.org or follow our WeChat official Account or Twitter, so we can have a better discussion

**Pull request closed without merging**
