### PR TITLE
fix: Refactor code by removing license header

### PR DESCRIPTION
**Pull request by wangsizhu0504**
> Associated PR: https://github.com/apache/incubator-streampark/pull/3323

  The frontend of streampark is based on an open-source frontend project: vue-vben-admin(https://github.com/vbenjs/vue-vben-admin). Some files were directly copied from the source code of vue-vben-admin. These copied files had an Apache License header. However, This does not comply with license requirements. Therefore, we removed the License Header from these copied files and keep the Apache License Header to our own code files. more details are as follows:

1. The source code of all files in the following files or folders from the vue-vben-admin project.

streampark-console/streampark-console-webapp/build/**
streampark-console/streampark-console-webapp/src/components/**
streampark-console/streampark-console-webapp/src/directives/**
streampark-console/streampark-console-webapp/src/logics/**
streampark-console/streampark-console-webapp/src/utils/**
streampark-console/streampark-console-webapp/src/App.vue
streampark-console/streampark-console-webapp/src/main.ts
streampark-console/streampark-console-webapp/src/locales/helper.ts
streampark-console/streampark-console-webapp/src/locales/setupI18n.ts
streampark-console/streampark-console-webapp/src/locales/useLocale.ts
streampark-console/streampark-console-webapp/src/views/base/error-log/**
streampark-console/streampark-console-webapp/src/views/base/exception/**
streampark-console/streampark-console-webapp/src/views/base/lock/**
streampark-console/streampark-console-webapp/src/views/base/redirect/**
streampark-console/streampark-console-webapp/src/enums/**
streampark-console/streampark-console-webapp/src/design/**
streampark-console/streampark-console-webapp/src/hooks/**
streampark-console/streampark-console-webapp/src/layouts/**
streampark-console/streampark-console-webapp/src/router/**
streampark-console/streampark-console-webapp/src/settings/**
streampark-console/streampark-console-webapp/src/store/**
streampark-console/streampark-console-webapp/types/**

2. useAttrs The built-in hooks for data in vue3 don't need to be written separately, but need to be removed in this PR (https://vuejs.org/api/sfc-script-setup.html#useslots-useattrs). The affected files are

  streampark-console/streampark-console-webapp/src/components/Button/src/BasicButton.vue
  streampark-console/streampark-console-webapp/src/components/Button/src/PopConfirmButton.vue
  streampark-console/streampark-console-webapp/src/components/Description/src/Description.vue
  streampark-console/streampark-console-webapp/src/components/Drawer/src/BasicDrawer.vue
  streampark-console/streampark-console-webapp/src/components/Form/src/components/ApiRadioGroup.vue
  streampark-console/streampark-console-webapp/src/components/Form/src/components/ApiSelect.vue
  streampark-console/streampark-console-webapp/src/components/Form/src/components/RadioButtonGroup.vue
  streampark-console/streampark-console-webapp/src/components/Modal/src/components/Modal.tsx

### CODE REVIEW

**Review by wolfboys — DISMISSED** [review]
LGTM

**Comment by wangsizhu0504** [comment]
cc @caicancai @wolfboys Changes to the license header in dev-2.1.2 have been synchronized

**Review by caicancai — APPROVED** [review]

**Comment by caicancai** [comment]
LGTM+1

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
