### PR TITLE
flink cluster improvement

### PR DESCRIPTION
**Pull request by wolfboys**
flink cluster improvement

### CODE REVIEW

**Comment by wolfboys** [comment]
cc @xujiangfeng001 PTAL , thx

**Comment by xujiangfeng001** [comment]
Hi @wolfboys ，thank you for your hard work. LGTM.

**Comment by wolfboys** [comment]
cc @RocMarshal PTAL. thx

**Review by muchunjin — APPROVED** [review]
LGTM

**Pull request merged**
