### PR TITLE
[Improve][All] Improvement of deprecated annotation

### PR DESCRIPTION
**Pull request by wuchunfu**
All `@deprecated` annotations in the warehouse need to be replaced with `@Deprecated` annotations.

Reason: When `@deprecated` is mixed in java/scala, the method call will not be unreliable.

### CODE REVIEW

**Comment by RocMarshal** [comment]
Hi, @wuchunfu thanks for the contribution.
[review-diff.txt](https://github.com/apache/incubator-streampark/files/13063660/review-diff.txt)

I left a few comments. PTAL in your free time~

**Review by RocMarshal — DISMISSED** [review]
@wuchunfu Thanks for the update!
LGTM +1.
I'll merge it after CI passed.

**Comment by wuchunfu** [comment]
> @wuchunfu Thanks for the update! LGTM +1. I'll merge it after CI passed.

Thanks @RocMarshal  for the review, I have fixed it, please review it here, thank you

**Review by RocMarshal — APPROVED** [review]
LGTM +1~

**Pull request merged**
