### PR TITLE
[improve] hadoop sample support

### PR DESCRIPTION
**Pull request by wolfboys**
[improve] hadoop sample support

## Contribution Checklist

hadoop sample support, [hadoop Authentication doc](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/HttpAuthentication.html)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by wolfboys** [comment]
cc @zhoulii @macksonmu PTAL, thx

**Comment by zhoulii** [comment]
Tested, works well. But It seems, with or without this change, there are no abnormal issues when enable `simple` Authentication.

**Comment by wolfboys** [comment]
> Tested, works well. But It seems, with or without this change, there are no abnormal issues when enable `simple` Authentication.

enable sample authentication in Hadoop generally does not require any special handling. However, recently there has been feedback from users in the community that related requests need to carry the `user.name` parameter to function properly.

**Review by muchunjin — COMMENTED** [review]
LGTM

**Review by muchunjin — APPROVED** [review]
LGTM

**Pull request merged**
