### PR TITLE
change deploy/docker/docker-compose image tag to dev

### LINKED ISSUE #3247: [Feature] change deploy/docker/dockercompose image tag to dev
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

There is no arm64 arch in latest image, which cause problem in Mac M2.
image

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by MingkeVan**
## What changes were proposed in this pull request

Issue Number: close #3247  

## Brief change log

*Change deploy/docker/docker-compose image tag to dev*

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (no)

### CODE REVIEW

**Review by caicancai — APPROVED** [review]

**Review by caicancai — CHANGES_REQUESTED** [review]
We will fix this bug later

**Comment by wolfboys** [comment]
Thanks very much for your feedback! Currently, our strategy for push images is to only push the image file when the official version is released. The "dev" branch is the development branch that has not been officially released yet, and it contains many unstable codes. We will not push this unstable code to Docker Hub and label it as "latest". The current "latest" version represents the last official version. 

We will fix this issue later in release-2.1.1 (the latest release version) and push the image to docker.

**Comment by caicancai** [comment]
Hello, thank you very much for finding this issue, indeed in 2.1.1 this branch build docker image does not support arm64, in the upcoming release of 2.1.2 has fixed this bug. Since 2.1.1 has been released and runs stably, it is not good to rebuild the image, which is not friendly to other users, you can try to build this image locally and use it. By the way, Streampark is very optimized for Mac m2 support.
This PR will be shut down
CC @wolfboys @MingkeVan

**Comment by wolfboys** [comment]
> Hello, thank you very much for finding this issue, indeed in 2.1.1 this branch build docker image does not support arm64, in the upcoming release of 2.1.2 has fixed this bug. Since 2.1.1 has been released and runs stably, it is not good to rebuild the image, which is not friendly to other users, you can try to build this image locally and use it. By the way, Streampark is very optimized for Mac m2 support. This PR will be shut down CC @wolfboys @MingkeVan

okay

**Pull request closed without merging**
