### PR TITLE
[Bug] alarm test bug fixed

### PR DESCRIPTION
**Pull request by wolfboys**
[Bug] alarm test bug fixed

## What changes were proposed in this pull request

Issue Number: close #xxx 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): no

### CODE REVIEW

**Comment by 1996fanrui** [comment]
Could you add som background? I don't know why need to change these code.

**Comment by wolfboys** [comment]
> Could you add som background? I don't know why need to change these code.

you can see: `AlertServiceImpl` line 81 for more detail.

**Comment by 1996fanrui** [comment]
> > Could you add som background? I don't know why need to change these code.
> 
> you can see: `AlertServiceImpl` line 81 for more detail.

After I see, I think current code can fix bug. However, I don't think it's a good solution.

The code is very unclear. Except for the developer himself, no one else may know that the name is used to find the service. That why you write a bug in #2023 

Clear code can reduce a lot of bugs, don't write a lot of implicit constraints.

**Comment by 1996fanrui** [comment]
I've seen too many bugs caused by implicit constraints in StreamPark. Every logic should have some code to implement, instead of implementing features by naming.

Long-term tolerance of low-quality code will make the project very difficult to maintain in the future, and very prone to bugs.

**Comment by wolfboys** [comment]
> I've seen too many bugs caused by implicit constraints in StreamPark. Every logic should have some code to implement, instead of implementing features by naming.
> 
> Long-term tolerance of low-quality code will make the project very difficult to maintain in the future, and very prone to bugs.

I agree with your point of view. The work of code cleaning will be carried out after the release of the first apache version, and later as more and more contributors, the quality will be strictly required.

**Comment by wolfboys** [comment]
cc @1996fanrui PTAL again, thanks

**Review by 1996fanrui — APPROVED** [review]
Thanks for your update.

LGTM

**Pull request merged**
