### PR TITLE
[WIP][Feature] Support Flink 1.18 application submit

### PR DESCRIPTION
**Pull request by ChengJie1053**
Support Flink 1.18 application submit

issues: https://github.com/apache/incubator-streampark/issues/3166

### CODE REVIEW

**Comment by Al-assad** [comment]
@ChengJie1053  Please note that there are some compilation errors at https://github.com/apache/incubator-streampark/actions/runs/6282946517/job/17062928571?pr=3169#step:4:4468

**Comment by ChengJie1053** [comment]
> https://github.com/apache/incubator-streampark/actions/runs/6282946517/job/17062928571?pr=3169#step:4:4468

Ok, thanks for reviewing the code，It is because maven warehouse does not have flink-1.18 dependency for the time being

**Comment by wolfboys** [comment]
Thanks for your contribution

**Comment by wolfboys** [comment]
Thanks for your contribution. There are some code style issues, please fix it first. https://github.com/apache/incubator-streampark/actions/runs/6622142106/job/17987202488?pr=3169

**Comment by ChengJie1053** [comment]
> Thanks for your contribution. There are some code style issues, please fix it first. https://github.com/apache/incubator-streampark/actions/runs/6622142106/job/17987202488?pr=3169

Ok, thank you for reviewing the code

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
