### PR TITLE
[Improve] Make the create time equal to update time when create a application

### LINKED ISSUE #3549: [improvement] make the ```create time``` equal to ```update time ``` when create a application
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

image
i think use ```appParam.setCreateTime(new Date());
    appParam.setModifyTime(appParam.getCreateTime()); ``` is better

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by caicancai**
## What changes were proposed in this pull request

Issue Number: close #3549 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Comment by fuchanghai** [comment]
+1

**Review by fuchanghai — APPROVED** [review]
+1

**Comment by VampireAchao** [comment]
https://github.com/apache/incubator-streampark/issues/3549

**Review by VampireAchao — APPROVED** [review]
LGTM

**Comment by caicancai** [comment]
Thank you for your review

**Comment by VampireAchao** [comment]
It's worth noting that in extreme cases, new Date() instances may have slight differences due to the time between their instantiations.So I agree this change.

**Pull request merged**
