### PR TITLE
Add i18n support for flink app menu

### PR DESCRIPTION
**Pull request by green241**
Add i18n support for flink app menu(ps:Recent continuous improvement).

### CODE REVIEW

**Comment by wangsizhu0504** [comment]
Thank you for your contribution. It is recommended that you create a new branch with the latest code and modify it on the new branch before submitting it to avoid code conflicts.

**Comment by green241** [comment]
Well, if there is a conflict in the code,  this pr need to be closed.

This is indeed a problem. In fact, when changing this part of the code, it is usually done at night, and the latest corresponding branch code is pulled before submitting. If there is a conflict, it will be resolved before submitting.

However, there is a problem. For example, a developer submits the code first but does not merge it. At this time, when another developer submits the code, it cannot pull the code to be merged by the previous developer.

Anyway, I'm still very happy that streampark is gradually improving, come on!

**Comment by wangsizhu0504** [comment]
In fact, I have never encountered such incidents. However, the correct thing is that you need to pull the latest code on the branch you modify, manually resolve the conflict, and then submit the post-conflict code. 
  
  But I seem to find that you didn't indicate a conflict. Let me check your submission first. If there is no problem, I will merge it. Thank you very much!

**Review by wangsizhu0504 — APPROVED** [review]
LGTM! Thank you very much for your contribution

**Comment by green241** [comment]
> In fact, I have never encountered such incidents. However, the correct thing is that you need to pull the latest code on the branch you modify, manually resolve the conflict, and then submit the post-conflict code.
> 
> But I seem to find that you didn't indicate a conflict. Let me check your submission first. If there is no problem, I will merge it. Thank you very much!

oka, i will check my local branch. Thx

**Pull request merged**
