### PR TITLE
[Improve] Related app release: LanuchState change to ReleaseState

### LINKED ISSUE #2366: [Improve] Related app release: LanuchState change to ReleaseState
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently in streampark, a job must go through a release process before starting. The current release process is called "Lanuch", and the release state is called "lanuch-state". The expression is not accurate and needs to be changed to "release-xxx".

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wolfboys**
Currently in streampark, a job must go through a release process before starting. The current release process is called "Lanuch", and the release state is called "lanuch-state". The expression is not accurate and needs to be changed to "release-xxx".

## What changes were proposed in this pull request

Issue Number: close #2366 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): no

### CODE REVIEW

**Comment by wolfboys** [comment]
cc @macksonmu @1996fanrui @wangsizhu0504 PTAL, thx.

**Comment by muchunjin** [comment]
`Release` is a keyword, you need to use backticks in sql, for example select \`release\`
图片

**Comment by wolfboys** [comment]
> `Release` is a keyword, you need to use backticks in sql, for example select `release` 图片

thanks for your check and review. I'll fixed it

**Review by muchunjin — APPROVED** [review]
LGTM

**Comment by wolfboys** [comment]
thanks for your review

**Pull request merged**
