### PR TITLE
[Bug] docker build project fail fixed

### PR DESCRIPTION
**Pull request by wellCh4n**
## What problem does this PR solve?

Issue Number: close #[1714](https://github.com/apache/incubator-streampark/issues/1714)

Problem Summary:

## What is changed and how it works?

Proposal: [xxx](url) 

Feel free to ping committers for the review!

## Contribution Checklist

  - Make sure that the pull request corresponds to a [GITHUB issue](https://github.com/apache/streampark/issues).

  - Name the pull request in the form "[Feature] [component] Title of the pull request", where *Feature* can be replaced by `Hotfix`, `Bug`, etc.

  - Minor fixes should be named following this pattern: `[hotfix] [docs] Fix typo in README.md doc`.

### CODE REVIEW

**Comment by wolfboys** [comment]
cc @MonsterChenzhuo If you are free, please check this pr

**Comment by MonsterChenzhuo** [comment]
@wellCh4n 图片
There are still a lot of problems inside, and if you have the conditions, you can explore how docker compose can control the type of database

https://streampark.apache.org/zh-CN/docs/user-guide/docker-deployment
Here is the official documentation, I think you can check it out and fix the documentation accordingly

**Comment by MonsterChenzhuo** [comment]
If you feel that you can't solve the problem I'm talking about for a while, you can also raise it, and I'll merge the content you submit when you start first.

**Comment by wellCh4n** [comment]
@MonsterChenzhuo Sure, I will try this holiday. But I think you need to merge first, because building failure is a bug, and multiple datasouce is a feature.
By the way, I added a command in Chinese documentation in doc repo and committed RP ago. https://github.com/apache/incubator-streampark-website/pull/149
image

**Comment by MonsterChenzhuo** [comment]
LGTM

**Review by MonsterChenzhuo — APPROVED** [review]

**Pull request merged**
