### PR TITLE
 [Improve] [Flink-Kubernetes-V2] Updated the crd of flink-operator 1.16.1

### PR DESCRIPTION
**Pull request by caicancai**
## What changes were proposed in this pull request

Updated the crd of flink-operator 1.16.1

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Comment by caicancai** [comment]
At present, the upstream support is not perfect, so I will pay attention to the upstream flink1.18 support and modify it. It is currently the WIP version

**Comment by caicancai** [comment]
Currently Flink-operator 1.16 supports flink1.18, but flink1.18 cannot be supported during my testing
cc @Al-assad @wolfboys

**Comment by Al-assad** [comment]
> Currently Flink-operator 1.16 supports flink1.18, but flink1.18 cannot be supported during my testing cc @Al-assad @wolfboys

Hi Cai, Flink Operator does not provide support for Flink 1.18 version currently. But if you want to preparation in advance, you can copy the corresponding crds yaml files to streampark-flink-crd/resources.

**Comment by caicancai** [comment]
@Al-assad Hi assad, Thank you for your reply. At present, I am doing this. I find that it does not affect the previous V2 code. I'm not sure if this code is currently suitable for merging.
cc @wolfboys

**Comment by caicancai** [comment]
cc @Al-assad @wolfboys Hi,I updated the crd of flink-operator 1.16.1. It seems that there are no major changes at present. You can consider merging it.

**Comment by caicancai** [comment]
@wolfboys He is able to merge without affecting the main process, and I am afraid that it will cause conflicts if it hangs for too long

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
