### PR TITLE
[WIP][Improve] Add e2e identifier for create and edit actions button

### PR DESCRIPTION
**Pull request by zhengkezhou1**
## What changes were proposed in this pull request

Issue Number: close #xxx 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Comment by zhengkezhou1** [comment]
flink-home, extlink, alarm etc components ' submit and cancel buttons look like not visible

**Comment by zhengkezhou1** [comment]
Hi @wolfboys any suggestions for me?

**Comment by wolfboys** [comment]
> Hi @wolfboys any suggestions for me?

LGTM

**Comment by wolfboys** [comment]
Thanks for your contribution. This PR has a lot of conflicts. Other PRs have already made most of the improvements. It would be best for you to submit a new PR to resolve this issue.

**Pull request closed without merging**
