### PR TITLE
'executionMode' should be set to null and fix 'kubernetes Pods Templa…

### PR DESCRIPTION
**Pull request by xinzhuxiansheng**
…te is not editable'

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

'executionMode' should be set to null and fix 'kubernetes Pods Template is not editable'

### CODE REVIEW

**Comment by xinzhuxiansheng** [comment]
Switch'Development Mode' and'Execution Mode', it will reappear kubernetes Pods Template is not editable

在作业添加表单页面 ，切换 'Development Mode' 和 'Execution Mode'，会出现 kubernetes Pods Template is not editable

**Comment by xinzhuxiansheng** [comment]
Switch 'Development Mode' ,default  'executionMode'  is set to null

**Review by Al-assad — APPROVED** [review]
LGTM.

**Comment by wolfboys** [comment]
LGTM.

**Pull request merged**
