### PR TITLE
[Improve] cleanup duplicate licenses

### PR DESCRIPTION
**Pull request by wolfboys**
[Improve] cleanup duplicate licenses

### CODE REVIEW

**Comment by wolfboys** [comment]
cc @WillemJiang PTAL, if you have free time, thanks

**Comment by WillemJiang** [comment]
Please keep the file 'dist-material/release-docs/licenses/license-asm-asm.txt'， it‘s empty now.
BTW, how do you store the front-end license in the binary release kit?

**Comment by wolfboys** [comment]
> Please keep the file 'dist-material/release-docs/licenses/license-asm-asm.txt'， it‘s empty now. BTW, how do you store the front-end license in the binary release kit?


thanks for your review.

added license-asm-asm.txt file.
front-end license: https://github.com/apache/incubator-streampark/tree/dev/dist-material/release-docs/licenses/front-end

please review it again if you have free time. thanks

**Comment by WillemJiang** [comment]
ASM is released under the following 3-Clause BSD License:
Please move the asm license from 2-Clause BSD License to 3-Clause BSD.

**Comment by WillemJiang** [comment]
We don't need to ship the Apache license in the license directory as they are the same.  Please clean up the third-party project licenses if they are Apache License V2.

**Comment by wolfboys** [comment]
> ASM is released under the following 3-Clause BSD License: Please move the asm license from 2-Clause BSD License to 3-Clause BSD.

done.

**Comment by wolfboys** [comment]
> We don't need to ship the Apache license in the license directory as they are the same. Please clean up the third-party project licenses if they are Apache License V2.

thanks for your review. i will fix it quickly

**Comment by wolfboys** [comment]
> We don't need to ship the Apache license in the license directory as they are the same. Please clean up the third-party project licenses if they are Apache License V2.

thanks for your review. 
all done,  third-party project Apache V2 License file removed.

**Comment by wolfboys** [comment]
cc @WillemJiang thanks for your review. happy new year! 🎈   please review it again if you have free time. thanks.

**Review by tisonkun — APPROVED** [review]

**Comment by WillemJiang** [comment]
As the License file is not a pure Apache License， it's better to provide the Apache License link in the below section of the License file.

image

**Comment by tisonkun** [comment]
@WillemJiang the content of Apache License is already present in the beginning of that file.

**Pull request merged**
