### PR TITLE
[Feat][Flink-K8s-V2] Adaptation of snapshot tracking for Flink on Kubernetes

### LINKED ISSUE #2885: [Feature] [Flink-K8s-V2] Refactor the state tracking of Flink on Kubernetes
It is a subtask of #2879.

Ref: [design doc](https://www.craft.me/s/LrTTzYHqSOLYqY)

### PR DESCRIPTION
**Pull request by Al-assad**
## What changes were proposed in this pull request

Issue Number: close #2885 #2883 
<br/>
## Brief change log

- Resolve the Maven mixed Java and Scala code compilation error in `streampark-console-service` module.
- Add a field named "k8sname" to the `Application` entity  to identify the corresponding K8s CR name.
- Provide startup recovery for the new Flink K8s subscriber.
- Optimize the FlinkChangeListenerV2 code written in PR #2989 
    - Reduce backpressure on subscription fibers through `ZStream.grouby`.
    - Correct the wrong way of writing SpringBoot Component in Scala.
    - Move the startup behavior of the subscription fibers to the SpringBoot `@PostConstruct` phase, and correctly interrupt it in the `@PreDestroy` phase.
- Fix some code issue in PR #3041.

<br/>

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): no

<br/>

### CODE REVIEW

**Comment by Al-assad** [comment]
@ChengJie1053  
Hi Cheng, This PR includes optimizations for your PR #2989， `FlinkK8sChangeListenerV2` has been renamed to `FlinkK8sObserverBroker`. Include the following points:
- Reduce backpressure on subscription fibers through ZStream.grouby.
- Correct the wrong way of writing SpringBoot Component in Scala.
- Move the startup behavior of the subscription fibers to the SpringBoot @PostConstruct phase, and correctly interrupt it in the @PreDestroy phase.

See https://github.com/apache/incubator-streampark/pull/3048/files#diff-dd6f00b9a900099a456a69babc2cc806da8ebe68183511324a143cbf31723319 for more.

**Comment by Al-assad** [comment]
@caicancai This PR also includes bug fixes for your PR #3041 :
- KuebernetesSessionClientV2 https://github.com/apache/incubator-streampark/pull/3048/files#diff-f378db5e73fc75860c2ef6f8aab262b3be9afa5863f13cca9fafd169946cbbf8
- FlinkClientHandler https://github.com/apache/incubator-streampark/pull/3048/files#diff-61c1a0c645609e3b2581c42497a6547e41319e1eb93ec5b7f59f256d7a856b20

**Comment by ChengJie1053** [comment]
> @ChengJie1053 Hi Cheng, This PR includes optimizations for your PR #2989， `FlinkK8sChangeListenerV2` has been renamed to `FlinkK8sObserverBroker`. Include the following points:
> 
> * Reduce backpressure on subscription fibers through ZStream.grouby.
> * Correct the wrong way of writing SpringBoot Component in Scala.
> * Move the startup behavior of the subscription fibers to the SpringBoot @PostConstruct phase, and correctly interrupt it in the @PreDestroy phase.
> 
> See https://github.com/apache/incubator-streampark/pull/3048/files#diff-dd6f00b9a900099a456a69babc2cc806da8ebe68183511324a143cbf31723319 for more.

Ok, thank you

**Comment by caicancai** [comment]
> @caicancai This PR also includes bug fixes for your PR #3041 :
> 
> * KuebernetesSessionClientV2 https://github.com/apache/incubator-streampark/pull/3048/files#diff-f378db5e73fc75860c2ef6f8aab262b3be9afa5863f13cca9fafd169946cbbf8
> * FlinkClientHandler https://github.com/apache/incubator-streampark/pull/3048/files#diff-61c1a0c645609e3b2581c42497a6547e41319e1eb93ec5b7f59f256d7a856b20

Thank you

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
