### PR TITLE
Update README_CN.md

### PR DESCRIPTION
**Pull request by wolfboys**
Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

Feel free to ping committers for the review!

## Contribution Checklist

  - Make sure that the pull request corresponds to a [GITHUB issue](https://github.com/apache/streampark/issues).

  - Name the pull request in the form "[Feature] [component] Title of the pull request", where *Feature* can be replaced by `Hotfix`, `Bug`, etc.

  - Minor fixes should be named following this pattern: `[hotfix] [docs] Fix typo in README.md doc`.

### CODE REVIEW

**Comment by 1996fanrui** [comment]
LGTM

**Comment by wolfboys** [comment]
@Al-assad PTAL, At least 1 approving review is required.

**Review by lvshaokang — APPROVED** [review]

**Comment by lvshaokang** [comment]
@wolfboys LGTM. Thanks

**Comment by Al-assad** [comment]
> @Al-assad PTAL, At least 1 approving review is required.

Unfortunately, it seems that I haven’t been assigned project writing privilege. 🥲

**Review by liuzhuang2017 — APPROVED** [review]
LGTM

**Comment by wolfboys** [comment]
@tisonkun PTAL thx✌️

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
