### PR TITLE
[Bug][Get Yarn Proxy] delete result data value '/cluster/app'

### PR DESCRIPTION
**Pull request by sdhzwc**
#3030 
Below is a demonstration of the comparison before and after the repair:

一、Before repair
修改前yarn
applicatid

修改
![applicatid
前动态](https://github.com/apache/incubator-streampark/assets/46134044/f6eaf7be-8b58-445b-8ec1-39a60f6e45fa)

二、After repair
修改后yarn
修改后 appli id
修改后模式

### CODE REVIEW

**Comment by wolfboys** [comment]
hi :

Thanks very much for your contribution. Please first open an issue and provide the relevant environment and version info:
1. Which scala version of StreamPark ?
2. What deployment mode?
3. What versions of Hadoop and Yarn respectively?

StreamPark 2.1.1 has been running in many people's production environments. There may be bugs with different versions of Yarn.  BTW, the community only accepts requests in English. Please use English next time. 😊

**Comment by sdhzwc** [comment]
> hi :
> 
> Thanks very much for your contribution. Please first open an issue and provide the relevant environment and version info:
> 
> 1. Which scala version of StreamPark ?
> 2. What deployment mode?
> 3. What versions of Hadoop and Yarn respectively?
> 
> StreamPark 2.1.1 has been running in many people's production environments. There may be bugs with different versions of Yarn. BTW, the community only accepts requests in English. Please use English next time. 😊

My English is not very good and has been changed. Can you take a look and see if there is anything else I need to add

**Comment by wolfboys** [comment]
> > hi :
> > Thanks very much for your contribution. Please first open an issue and provide the relevant environment and version info:
> > 
> > 1. Which scala version of StreamPark ?
> > 2. What deployment mode?
> > 3. What versions of Hadoop and Yarn respectively?
> > 
> > StreamPark 2.1.1 has been running in many people's production environments. There may be bugs with different versions of Yarn. BTW, the community only accepts requests in English. Please use English next time. 😊
> 
> My English is not very good and has been changed. Can you take a look and see if there is anything else I need to add


Thank you for your addition, we will review it as soon as possible. ✍️

**Comment by wolfboys** [comment]
cc @macksonmu @zhoulii PTAL, thx

**Comment by muchunjin** [comment]
@sdhzwc This problem has been fixed in the upcoming 2.1.2. You can try the dev-2.1.2 branch. For details, please see https://github.com/apache/incubator-streampark/commit/28d06fc0e7724d267aa0957517f4626307c9643b. If you still have problems please contact me directly.

**Pull request closed without merging**
