### PR TITLE
[Bug] Some DDLs of t_setting are missed

### LINKED ISSUE #1813: [Bug] Some DDLs of t_setting are missed
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

12.3 mysql schema link:  https://github.com/apache/incubator-streampark/blob/e47b0d0be9922021a65c29b71c10faa4c85ae29c/streamx-console/streamx-console-service/src/assembly/script/final.sql#L495

Some fileds name of `t_setting` table are changed, but the [upgrade/mysql/1.2.4.sql](https://github.com/apache/incubator-streampark/blob/dev/streampark-console/streampark-console-service/src/assembly/script/upgrade/mysql/1.2.4.sql) doesn't include these changes. 

It's a bug, when streampark is upgrade from 1.2.3 to 1.2.4, it cannot work.

1.2.3 `t_setting` schema:

```mysql
DROP TABLE IF EXISTS `t_setting`;
CREATE TABLE `t_setting` (
`NUM` int DEFAULT NULL,
`KEY` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
`VALUE` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
`TITLE` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
`DESCRIPTION` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
`TYPE` tinyint NOT NULL COMMENT '1: input 2: boolean 3: number',
PRIMARY KEY (`KEY`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
```

1.2.4 `t_setting` schema: 

```mysql
create table `t_setting` (
  `order_num` int default null,
  `setting_key` varchar(50) collate utf8mb4_general_ci not null,
  `setting_value` text collate utf8mb4_general_ci default null,
  `setting_name` varchar(255) collate utf8mb4_general_ci default null,
  `description` varchar(255) collate utf8mb4_general_ci default null,
  `type` tinyint not null comment '1: input 2: boolean 3: number',
  primary key (`setting_key`) using btree
) engine=innodb default charset=utf8mb4 collate=utf8mb4_general_ci;
```

### StreamPark Version

1.2.4

### Java Version

_No response_

### Flink Version

all

### Scala Version of Flink

all

### Error Exception

```log
all
```

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by shangeyao**
What changes were proposed in this pull request
Issue Number: close #1813 

Brief change log
add DDL of t_setting upgrade

Verifying this change
add DDL of t_setting upgrade

Does this pull request potentially affect one of the following parts
Dependencies (does it add or upgrade a dependency): no

### CODE REVIEW

**Comment by lvshaokang** [comment]
Hi, @shangeyao. Thanks for you contribute.
Please follow the PR template to describe the changes contributed by the pull request

**Comment by shangeyao** [comment]
> Hi, @shangeyao. Thanks for you contribute. Please follow the PR template to describe the changes contributed by the pull request

Done.

**Review by 1996fanrui — APPROVED** [review]
Good job, @shangeyao , thanks for your contribution. Looking forward to your next contribution.

**Comment by 1996fanrui** [comment]
Hi @lvshaokang , I have ran this `upgrade.sql` in my Local MySQL docker. It works well. Please help double check and merge this PR, thanks~

**Review by lvshaokang — APPROVED** [review]
+1, LGTM. Merging to dev.
@shangeyao Thank you

**Pull request merged**
