### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by ADHIRAJ-12**
readme typo fixed

### CODE REVIEW

**Comment by caicancai** [comment]
@ADHIRAJ-12 Hi，Thank you for your contribution, but the PR you mentioned seems to have changed the code in other places, and the scope of the changes is relatively large. Is it put together due to other needs?

**Review by caicancai — COMMENTED** [review]
Hello, can README changes and code changes be submitted in two separate PRs?

**Comment by ADHIRAJ-12** [comment]
hey @caicancai,i just fixed the typo  and created the PR for that,but when i forked the project initaially , it was showing some changes in all the files,even before i touched anything. @wolfboys

**Comment by caicancai** [comment]
> hey @caicancai,i just fixed the typo and created the PR for that,but when i forked the project initaially , it was showing some changes in all the files,even before i touched anything.

Hello, this error has been fixed at https://github.com/apache/incubator-streampark/pull/3293. We will merge it first. Thank you for your contribution. By the way, there are currently many good first issues in the community and you are welcome to participate. If you have any questions, you can directly @ me

**Comment by ADHIRAJ-12** [comment]
thanks @caicancai

**Comment by wolfboys** [comment]
Thanks very much for your contribution! I noticed that a lot of files were accidentally modified and deleted.  Could you please double-check? I'm really looking forward to seeing your PR again, Your contribution to streampark is highly welcome! 🎉

**Comment by ADHIRAJ-12** [comment]
hey @wolfboys ,i  just explained what happened about all the files getting modified.

**Comment by wolfboys** [comment]
> hey @wolfboys ,i just explained what happened about all the files getting modified.

Thanks for clarification. I'll take a look at the branch you've submitted the PR(https://github.com/ADHIRAJ-12/incubator-streampark/tree/readmeedit), many files have been deleted and are very different from the dev branch. Perhaps it was caused by accidental operations. 😅 so, I will close the current PR and you can resubmit a PR

image

**Comment by ADHIRAJ-12** [comment]
Thanks @wolfboys

**Pull request closed without merging**
