### PR TITLE
[Bug] After switch groups, the metrics dashboard info is not switched…

### LINKED ISSUE #2315: [Bug] After switching groups, the monitoring dashboard information is not switched correctly.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

After switching groups, the monitoring dashboard information is not switched correctly.

Firstly, I created two flink tasks with the user admin in default group.
image

However ,when switching the group from default to test which I had creeated, the monitoring dashboard showing as following,

image

Therefore, I feel it is a bug ,please check it.

**2023.2.16 add: this issue only appears in kubernetes mode , yarn mode is normal.**

### StreamPark Version

2.0.0

### Java Version

1.8.0_181

### Flink Version

1.14.3

### Scala Version of Flink

2.12

### Error Exception

```log
Referring the "what happened" module.
```

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wolfboys**
[Bug] After switch groups, the metrics dashboard info is not switched correctly
## What changes were proposed in this pull request

Issue Number: close #2315

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Comment by wolfboys** [comment]
cc @green241 PTAL, if you have free time. please test it.

**Comment by green241** [comment]
> cc @green241 PTAL, if you have free time. please test it.

I just tested it with the k8s-status branch and found that the dashboard does not properly show the resources occupied by the job when the job is successfully started; the same thing happens after switching groups.

Group: default
image

Group: test
image

**Comment by green241** [comment]
> > cc @green241 PTAL, if you have free time. please test it.
> 
> I just tested it with the k8s-status branch and found that the dashboard does not properly show the resources occupied by the job when the job is successfully started.
> 
> Group: default image
> 
> Group: test image

**Comment by green241** [comment]
After testing, this PR successfully fixed the [issue](https://github.com/apache/incubator-streampark/issues/2315)

Group: default. 2 running jobs:
image

Group: test. 1 running job:
image

**Comment by green241** [comment]
This issue had been resolved , [here](https://github.com/apache/incubator-streampark/pull/2376).

**Comment by wolfboys** [comment]
thanks for your review

**Review by muchunjin — APPROVED** [review]
LGTM

**Pull request merged**
