### PR TITLE
[Bug] dynamicProperties env.java.opts not support bug fixed

### LINKED ISSUE #1873: [Bug] env.java.opts on yarn not effict
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

env.java.opts on yarn application模式下不生效

### StreamPark Version

1.2.3

### Java Version

1.8

### Flink Version

1.13.6

### Scala Version of Flink

2.12

### Error Exception

```log
配置不生效
```

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wolfboys**
[Bug] dynamicProperties env.java.opts not support bug fixed

## What changes were proposed in this pull request

Issue Number: close #1873

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): no

### CODE REVIEW

**Comment by wolfboys** [comment]
cc @Al-assad  @xxyykkxx  @lwzhangMr PTAL, thanks

**Comment by MonsterChenzhuo** [comment]
LGTM

**Review by MonsterChenzhuo — APPROVED** [review]

**Review by monrg — APPROVED** [review]
LGTM

**Review by xxyykkxx — COMMENTED** [review]
LGTM

**Pull request merged**
