### PR TITLE
[Improve] Improve streampark-console module base on 3.6 Control/Condition Statements

### LINKED ISSUE #3069: [Improve] Improve `streampark-console` module base on [3.6 Control/Condition Statements]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Improve] Improve `streampark-console` module base on [3.6 Control/Condition Statements](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide#36-controlcondition-statements)

### Usage Scenario

_No response_

### Related issues

#2986

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by eagleli123**
## What changes were proposed in this pull request

Issue Number: close #3069 

## Brief change log

[Improve] Improve streampark-console module base on [3.6 Control/Condition Statements](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide#36-controlcondition-statements)

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (no)

### CODE REVIEW

**Comment by caicancai** [comment]
Hi , Thank you for your contribution. Could you please improve the title?  [Improve] Improve streampark-console module base on [3.6 Control/Condition Statements](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide#36-controlcondition-statements)

**Comment by eagleli123** [comment]
> Hi , Thank you for your contribution. Could you please improve the title? [Improve] Improve streampark-console module base on [3.6 Control/Condition Statements](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide#36-controlcondition-statements)

Thanks for the reminder, the title has been modified.

**Comment by caicancai** [comment]
cc @RocMarshal

**Review by RocMarshal — APPROVED** [review]
hi, @eagleli123  Thanks for your hard work.
LGTM +1.

**Pull request merged**
