### PR TITLE
[Improve][project-build] Limit the number of running build projects

### PR DESCRIPTION
**Pull request by zhilinli123**
## What changes were proposed in this pull request

Used to solve multiple projects while building cpu surges and improve machine stability

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Comment by zhilinli123** [comment]
img_v3_02a6_341893f8-55ef-4485-bc6c-809e4138ae0g
image

**Comment by caicancai** [comment]
@wolfboys PATL

**Comment by zhilinli123** [comment]
pre pull request :https://github.com/apache/incubator-streampark/pull/3679/files#diff-625e877ffa250d016d6edb0be3d702299e91eba563967b1731e502fb18ce2f15

@caicancai

**Comment by wolfboys** [comment]
hi, the config file application.yml is deprecated, I suggest setting this parameter in the system-settings page. Do not write it to the configuration file. 🛠️

**Pull request closed without merging**
