### PR TITLE
[Improve] adjust swagger api display range and only retain application op api.

### PR DESCRIPTION
**Pull request by lvshaokang**
## What changes were proposed in this pull request

adjust swagger api display range for security, only retain application op api.

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no) no

### CODE REVIEW

**Comment by lvshaokang** [comment]
cc @wolfboys PTAL.

**Review by caicancai — APPROVED** [review]
LGTM

**Comment by lvshaokang** [comment]
@wolfboys PTAL. Remove the @Tag/@Operation annotations and retain start/cancel as openapi

**Review by wolfboys — APPROVED** [review]
LGTM, Thanks for the great work

**Pull request merged**
