### PR TITLE
[Feature-3740] Add end-to-end test framework and User Management and Team Management test cases

### LINKED ISSUE #3740: [Feature] Add end-to-end test framework and User Management and Team Management test cases
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add end-to-end test framework and User Management and Team Management test cases

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## What changes were proposed in this pull request

Issue Number: close #3740

## Brief change log

1. Add end-to-end test framework
2. Add User Management test cases like testCreateUser,testCreateDuplicateUser,testEditUser
3. Add Team Management test cases like testCreateTeam,testCreateDuplicateTeam,testEditTeam,testDeleteTeam

### CODE REVIEW

**Comment by SbloodyS** [comment]
@caicancai @wolfboys PTAL.

**Comment by caicancai** [comment]
Cil failed

**Comment by SbloodyS** [comment]
> Cil failed

Both `maven-compile (java-11)` and `Dead links` errors were not caused by this PR, please check

**Review by wolfboys — APPROVED** [review]
LGTM, The CI failed, it was not caused by the current PR.  Merge this PR first.

**Pull request merged**
