### PR TITLE
[Improve] [Flink-Kubernetes-V2] Copy a trackCluster api to the trackApplication Job api

### PR DESCRIPTION
**Pull request by caicancai**
## What changes were proposed in this pull request
Copy a trackCluster api to the track Application Job api to improve code readability and avoid confusing Cluster and Application.

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Comment by caicancai** [comment]
This PR doesn't have to be merged as that might not be a good suggestion

**Comment by caicancai** [comment]
cc @Al-assad @wolfboys

**Review by Al-assad — CHANGES_REQUESTED** [review]
I don't quite understand the necessity of separately writing a `trackApplication` function. For Flink Operator, both Flink Cluster and Flink Application Job use a CRD resource called `FlinkDeployment`, and their tracking methods are the same.

**Comment by caicancai** [comment]
thank you your review

**Pull request closed without merging**
