### PR TITLE
[Improve] add probe enhancement for helm chart deploy.

### PR DESCRIPTION
**Pull request by lvshaokang**
## What changes were proposed in this pull request

Issue Number: close #xxx 

add probe template for helm chart deploy

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no) no

### CODE REVIEW

**Comment by lvshaokang** [comment]
cc @MonsterChenzhuo

**Comment by MonsterChenzhuo** [comment]
@lvshaokang  Are there any relevant tests?

**Comment by lvshaokang** [comment]
manual test, if enable probe, k8s dashboard will display the following as:

image

cc @MonsterChenzhuo

**Comment by MonsterChenzhuo** [comment]
LGTM

**Review by MonsterChenzhuo — APPROVED** [review]

**Pull request merged**
