### PR TITLE
[Bug] fix FlinkKubernetesClient.getService() bug

### PR DESCRIPTION
**Pull request by xbthink**
## What changes were proposed in this pull request

Closing k8s flink HA cluster will throw an ApiAlertException("Get shutdown response failed"), because we use directly clusterId as the service name at invoking `FlinkKubernetesClient.getService()`. We need convert clusterId to the service name by adding a suffix `-rest`.
This flink api changed at Flink-26112

## Verifying this change

- *Manually verified the change by testing locally.*

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (no)

### CODE REVIEW

**Comment by wolfboys** [comment]
Thanks for your contribution. We will review it as soon as possible  😊🙏

**Comment by wolfboys** [comment]
cc @Al-assad If you have time, please review the PR 😉

**Comment by Al-assad** [comment]
> cc @Al-assad If you have time, please review the PR 😉

Okay,I'll be back

**Review by Al-assad — CHANGES_REQUESTED** [review]
Good job 👍, @xbthink Can you optimize the relevant code of streampark-flink-shims_flink-1.15 and streampark-flink-shims_flink-1.17 modules in the same way?

**Comment by xbthink** [comment]
I don't quite understand your question, I double-check the relevant code of other flink-shims and I think we only need to modify the code of  streampark-flink-shims_flink-1.16 and  streampark-flink-shims_flink-1.17, right? @Al-assad

**Comment by Al-assad** [comment]
> I don't quite understand your question, I double-check the relevant code of other flink-shims and I think we only need to modify the code of streampark-flink-shims_flink-1.16 and streampark-flink-shims_flink-1.17, right? @Al-assad

I made a typo... you're spot on.

**Review by Al-assad — APPROVED** [review]

**Pull request merged**
