### PR TITLE
[Improve][Flink-Kubnernetes-V2] Improve UsingObserver test

### PR DESCRIPTION
**Pull request by caicancai**
## What changes were proposed in this pull request
 Add track and get flink job endpoint test
 Add session test

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Comment by caicancai** [comment]
I am checking and improving the Flink-Kubernetes-V2 backend test and expect to complete this part of the task tomorrow

**Comment by caicancai** [comment]
cc @wolfboys test success. At present, all backend interfaces have been completed

**Comment by caicancai** [comment]
@wolfboys PATL

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
