### PR TITLE
[Bug] yarn kerberos acl #1046

### PR DESCRIPTION
**Pull request by atovk**
Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

Feel free to ping committers for the review!

## Contribution Checklist

  - Make sure that the pull request corresponds to a [GITHUB issue](https://github.com/streamxhub/streamx/issues).

  - Name the pull request in the form "[Feature] [component] Title of the pull request", where *Feature* can be replaced by `Hotfix`, `Bug`, etc.

  - Minor fixes should be named following this pattern: `[hotfix] [docs] Fix typo in README.md doc`.

-->

### CODE REVIEW

**Comment by atovk** [comment]
@wolfboys TBR

**Comment by atovk** [comment]
add this net to add jvm -Djava.security.auth.login.config=jaas.conf

jaas.conf

```
httpClient {
      com.sun.security.auth.module.Krb5LoginModule required
      useKeyTab=true
      useTicketCache=false
      keyTab="/home/streamx/streamx-console-service/user01.keytab"
      principal="user01";
};
```

**Comment by wolfboys** [comment]
There are two problems:
1. httpclientUtils is a general http request tool. Kerberos will be used in big data scenarios, and directly changing httpclient will affect normal non-kerberos authentication requests. It is not suitable. The best way is to add http requested method in hadoopUtils, and supports kerberos authentication when call http method

2. The -Djava.security.auth.login.config=jaas.conf parameter setting can be moved to application.yml.

**Comment by wolfboys** [comment]
There are two problems:
1. httpclientUtils is a general http request tool. Kerberos will be used in big data scenarios, and directly changing httpclient will affect normal non-kerberos authentication requests. It is not suitable. The best way is to add http requested method in hadoopUtils, and supports kerberos authentication when call http method

2. The -Djava.security.auth.login.config=jaas.conf parameter setting can be moved to application.yml.

**Review by wolfboys — COMMENTED** [review]
LGTM.

**Comment by atovk** [comment]
we used streamx conf :
```
streamx:
  yarn:
    # default sample, or kerberos
    http-auth: sample

```
1. use common kerberos.yml principal/keytab(this principal mast in yarn acl list)
2. merge func to yarnUtils(request yarn http server)
3. add AuthHttpClientUtils, this httpClient use SPNEGO auth with kerberos

@wolfboys CR.

 thx

**Comment by wolfboys** [comment]
> we used streamx conf :
> 
> ```
> streamx:
>   yarn:
>     # default sample, or kerberos
>     http-auth: sample
> ```
> 
> 1. use common kerberos.yml principal/keytab(this principal mast in yarn acl list)
> 2. merge func to yarnUtils(request yarn http server)
> 3. add AuthHttpClientUtils, this httpClient use SPNEGO auth with kerberos
> 
> @wolfboys CR.
> 
> thx

LGTM. good job.

**Pull request merged**
