### PR TITLE
[Improve] table resize icon

### PR DESCRIPTION
**Pull request by wangsizhu0504**
## What changes were proposed in this pull request

Issue Number: close #xxx 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

1. app page form add column drag and drop icon, limit jobName column width to minimum 100px

https://github.com/apache/incubator-streampark/assets/39726513/3bc5b4bc-55ea-43e1-84b1-f6e4bcf4ba0a

image

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Comment by wangsizhu0504** [comment]
cc @wolfboys I have added drag and drop icons to the table columns in the app view interface.

**Review by wolfboys — APPROVED** [review]
LGTM

**Comment by caicancai** [comment]
@wangsizhu0504 Can you submit another PR to the dev branch, thank you

**Comment by wangsizhu0504** [comment]
> @wangsizhu0504 Can you submit another PR to the dev branch, thank you

ok！ I will submit a new PR later

**Pull request merged**
