### PR TITLE
[bug]Repair helm is unavailable

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
## What changes were proposed in this pull request

Issue Number: close #xxx 

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Comment by lvshaokang** [comment]
Hi @MonsterChenzhuo , could you add `livenessProbe` and `readinessProbe` section base on the helm template.
like this, refer[1]:
- livenessProbe
```
livenessProbe:
    exec:
        command: ["curl", "-s", "http://${host}:${port}/actuator/health/liveness"]
    initialDelaySeconds: 30
    periodSeconds: 30
    ......
```

- readinessProbe
```
readinessProbe:
    exec:
        command: ["curl", "-s", "http://${host}:${port}/actuator/health/readiness"]
    initialDelaySeconds: 30
    periodSeconds: 30
    ......
```

[1]. https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by MonsterChenzhuo** [comment]
> 你好 @MonsterChenzhuo, 你能加吗 `livenessProbe`和 `readinessProbe`基于 helm 模板的部分。 像这样，参考[1]：
> 
>     * 活性探针
> 
> 
> ```
> livenessProbe:
>     exec:
>         command: ["curl", "-s", "http://${host}:${port}/actuator/health/liveness"]
>     initialDelaySeconds: 30
>     periodSeconds: 30
>     ......
> ```
> 
>     * 就绪探针
> 
> 
> ```
> readinessProbe:
>     exec:
>         command: ["curl", "-s", "http://${host}:${port}/actuator/health/readiness"]
>     initialDelaySeconds: 30
>     periodSeconds: 30
>     ......
> ```
> 
> [1]. [https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ ](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)

Sorry about the probe part I'm not particularly clear, I hope to add it in the next version

**Comment by lvshaokang** [comment]
@MonsterChenzhuo , Is there a problem in this place?

https://github.com/apache/incubator-streampark/blob/18b1c8d6837d7cb060d832f5de2fa8bb93504ad0/deploy/helm/streampark/templates/streampark.yml#L61-L62

**Comment by wolfboys** [comment]
cc @lvshaokang about livenessProbe, we can do it in next pr

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
