### PR TITLE
[Feature] Update the username index for t_user table

### LINKED ISSUE #1684: [Feature] Update the index for t_user
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, the `nick_name` is the unique key for t_user. But : 

- we are using username instead of nickname in many places. 
- And the `nick_name` is the empty string in the `mysql-data.sql`.
- Front end doesn't allow the username is null

So I propose : 

- we change the unique key from `nick_name` to `username`
- and change the `username` not null.

The old index:

> unique key `un_username` (`nick_name`) using btree

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by 1996fanrui**
## What problem does this PR solve?

Issue Number: close #1684 

Problem Summary:

## What is changed and how it works?

Currently, the `nick_name` is the unique key for t_user. But : 

- we are using username instead of nickname in many places. 
- And the `nick_name` is the empty string in the `mysql-data.sql`.
- Front end doesn't allow the username is null

So I propose : 

- we change the unique key from `nick_name` to `username`
- and change the `username` not null.

The old index:

> unique key `un_username` (`nick_name`) using btree

The new index:

> unique key `un_username` (`username`) using btree

Feel free to ping committers for the review!

## Contribution Checklist

  - Make sure that the pull request corresponds to a [GITHUB issue](https://github.com/apache/streampark/issues).

  - Name the pull request in the form "[Feature] [component] Title of the pull request", where *Feature* can be replaced by `Hotfix`, `Bug`, etc.

  - Minor fixes should be named following this pattern: `[hotfix] [docs] Fix typo in README.md doc`.

### CODE REVIEW

**Comment by xinzhuxiansheng** [comment]
Hi @1996fanrui ,  thanks for your contribution.

Can you add a pgsql-upgrad.sql to the upgrade directory to record DDL and DML changes，`pgsql-schema.sql` also needs to update the `username index`

@1996fanrui @wolfboys 

upgrade directory, can we adjust it like dolphinscheduler upgrade sql?
E.g :
upgrade/(1.2.4-SNAPSHOT)\_schema/(mysql/pgsql)/streampark_(ddl/dml).sql

**Comment by 1996fanrui** [comment]
> Can you add a pgsql-upgrad.sql to the upgrade directory to record DDL and DML changes, `pgsql-schema.sql` also needs to update the `username index`

Hi @xinzhuxiansheng , thanks for your review. As I know, #1449 added the `pgsql-schema.sql` at Aug 2022.  `streampark-1.2.3` doesn't support pgsql, `streampark-1.2.4` will be the first version that supports pgsql. So I think we don't need to prepare the `pgsql-upgrade.sql` at this version. Please correct me if I'm wrong.

> upgrade directory, can we adjust it like dolphinscheduler upgrade sql? E.g : upgrade/(1.2.4-SNAPSHOT)_schema/(mysql/pgsql)/streampark_(ddl/dml).sql

Great idea, absolutely agree. I can do it. Should we update the directory in this PR or create a new PR to do it? I prefer create a new issue and PR.

Actually, it is not reasonable for some feature or bugfix or upgrade to be mixed into one commit. If a commit has a bug and needs to be rolled back, multiple features will be rolled back. In the long term, we also need the `Code Style and Quality Guide` like Flink : 

https://flink.apache.org/contributing/code-style-and-quality-pull-requests.html#separate-refactoring-cleanup-and-independent-changes

image

**Comment by lvshaokang** [comment]
> Great idea, absolutely agree. I can do it. Should we update the directory in this PR or create a new PR to do it? I prefer create a new issue and PR.
@1996fanrui I agree that,  we should create new issue to work.

**Comment by 1996fanrui** [comment]
> > Great idea, absolutely agree. I can do it. Should we update the directory in this PR or create a new PR to do it? I prefer create a new issue and PR.
> 
> @1996fanrui I agree that,  we should create new issue to work.

Hi @xinzhuxiansheng @lvshaokang  , I created a new issue #1687  to split `sql-upgrade.sql` into a different directory. I will do it after this PR is merged.

**Comment by wolfboys** [comment]
> > > Great idea, absolutely agree. I can do it. Should we update the directory in this PR or create a new PR to do it? I prefer create a new issue and PR.
> > 
> > 
> > @1996fanrui I agree that,  we should create new issue to work.
> 
> Hi @xinzhuxiansheng @lvshaokang , I created a new issue #1687 to split `sql-upgrade.sql` into a different directory. I will do it after this PR is merged.

very good proposal. i agree with you

**Review by wolfboys — APPROVED** [review]
LGTM

**Comment by xinzhuxiansheng** [comment]
> > Can you add a pgsql-upgrad.sql to the upgrade directory to record DDL and DML changes, `pgsql-schema.sql` also needs to update the `username index`
> 
> Hi @xinzhuxiansheng , thanks for your review. As I know, #1449 added the `pgsql-schema.sql` at Aug 2022. `streampark-1.2.3` doesn't support pgsql, `streampark-1.2.4` will be the first version that supports pgsql. So I think we don't need to prepare the `pgsql-upgrade.sql` at this version. Please correct me if I'm wrong.
> 
> > upgrade directory, can we adjust it like dolphinscheduler upgrade sql? E.g : upgrade/(1.2.4-SNAPSHOT)_schema/(mysql/pgsql)/streampark_(ddl/dml).sql
> 
> Great idea, absolutely agree. I can do it. Should we update the directory in this PR or create a new PR to do it? I prefer create a new issue and PR.
> 
> Actually, it is not reasonable for some feature or bugfix or upgrade to be mixed into one commit. If a commit has a bug and needs to be rolled back, multiple features will be rolled back. In the long term, we also need the `Code Style and Quality Guide` like Flink :
> 
> https://flink.apache.org/contributing/code-style-and-quality-pull-requests.html#separate-refactoring-cleanup-and-independent-changes
> 
> image

@1996fanrui  Thank you for your reply, i get it.

**Pull request merged**
