### PR TITLE
[Improve][Doc] Improve README.md

### PR DESCRIPTION
**Pull request by caicancai**
## What changes were proposed in this pull request

Corresponding to the Feature of the official website, I think the layout of the official website is better
2023-10-17 16-55-32屏幕截图

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)
 - no

### CODE REVIEW

**Comment by wolfboys** [comment]
cc @saLeox PTAL, thx

**Comment by caicancai** [comment]
cc @wolfboys @saLeox ,fix

**Comment by caicancai** [comment]
Later I will also repair a part of the official website

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
