### PR TITLE
[Feature] Added variable management menu to team admin role #1849

### LINKED ISSUE #1849: [Feature] Added variable management menu to team admin role
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In the variable management module, only the team admin has the permission to create, modify, and delete. The general developer only has the permission to view. In the initial state, the team admin needs to be granted the permission to create, modify, delete and view.

### Usage Scenario

_No response_

### Related issues

 [Feature] Add basic functionality of variable modules such as create, modify, delete, query and search #1779 

 [Proposal][Feature] Add variable management module #1477 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by muchunjin**
## What changes were proposed in this pull request

Issue Number: close #1849  

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Comment by muchunjin** [comment]
@1996fanrui I added this as you said yesterday, I have tested with team admin and developer account respectively，please see if that's the problem?

**Review by 1996fanrui — APPROVED** [review]
@macksonmu Thanks for your contribution.

LGTM.

@wolfboys please help double check, thanks.

**Review by wolfboys — APPROVED** [review]
LGTM

**Comment by wolfboys** [comment]
> @macksonmu Thanks for your contribution.
> 
> LGTM.
> 
> @wolfboys please help double check, thanks.

done

**Pull request merged**
