### PR TITLE
[Issue-2330]fix get user-defined maven settings.xml

### LINKED ISSUE #2330: [Bug] Invalid maven settings.xml
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

我设置了 maven文件，但没有生产，我debug了源码发现无法正常获取setting.xml

### StreamPark Version

2.0

### Java Version

8

### Flink Version

null

### Scala Version of Flink

2.12

### Error Exception

```log
null
```

### Screenshots

code path:  org/apache/streampark/console/core/entity/Project.java:207

image
image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #2339: [Refactor] Refactor FlinkClientHandler
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

# what
- Responsibility： The FlinkClientHandler is responsible for Flink client action, such as ,deploy, submit.... 
- The every method contains muti-case lines style， which makes it compatible with multiple execution mode

# why
A new method is added each time, it needs to follow the existing coding.
There is a certain amount of code bloat as methods are introduced as discussed in https://github.com/apache/incubator-streampark/pull/2268#discussion_r1103619008
# how
Wait for discussion.

### Usage Scenario

N.A

### Related issues

https://github.com/apache/incubator-streampark/pull/2268

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Inighty**
## What changes were proposed in this pull request

Issue Number: close #2330  

## Brief change log
Fix to get user-defined maven settings.

## Verifying this change

Manually verified the change by testing locally.

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): no

### CODE REVIEW

**Review by wolfboys — DISMISSED** [review]
LGTM

**Comment by wolfboys** [comment]
hi Inighty: please run:
`mvn -Pscala-2.11,console spotless:apply`
to fixed checkstyle issue

**Comment by Inighty** [comment]
> hi Inighty: please run: `mvn -Pscala-2.11,console spotless:apply` to fixed checkstyle issue

Thx for your code review, I have modified it.

**Comment by Inighty** [comment]
> hi Inighty: please run:
> 
> `mvn -Pscala-2.11,console spotless:apply`
> 
> to fixed checkstyle issue

Sorry for dismissed.I don't have much PR experience, please forgive me.

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
