### PR TITLE
[bug] Fixed the regular expression bug of flink on k8s cluster-id Validation

### PR DESCRIPTION
**Pull request by youyangkou**
## What changes were proposed in this pull request
Fixed the regular expression bug of flink on k8s cluster-id Validation
Issue Number: [2184](https://github.com/apache/incubator-streampark/issues/2184)

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Comment by green241** [comment]
hi  youyang,
The length and Uniqueness of the cluster id should also be paid attention, as following 
"The cluster-id, which should be **no more than 45 characters**, is used for identifying a **unique** Flink cluster. "
For example, when I typed 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' into this field ,it may show 'java.lang.IllegalArgumentException: kubernetes.cluster-id must be no more than 45 characters.'

**Comment by youyangkou** [comment]
> 



>

**Comment by youyangkou** [comment]
> hi youyang, The length and Uniqueness of the cluster id should also be paid attention, as following "The cluster-id, which should be **no more than 45 characters**, is used for identifying a **unique** Flink cluster. " For example, when I typed 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' into this field ,it may show 'java.lang.IllegalArgumentException: kubernetes.cluster-id must be no more than 45 characters.'

Thank you very much for your suggestion, I will consider adding this.

**Review by wangsizhu0504 — APPROVED** [review]
LGTM

**Pull request merged**
