### PR TITLE
[feature] SqlGateway base module

### PR DESCRIPTION
**Pull request by GOODBOY008**
WIP....

### CODE REVIEW

**Comment by wolfboys** [comment]
Great feature, looking forward to it, BTW, Can you add more information such as relevant proposals and designs?

**Comment by SteNicholas** [comment]
@wolfboys I would like to review this pull request. BTW, @GOODBOY008, could you squash the commits into one commit or split this pull request to multi pull requests? IMO, you could introduce the interfaces in this pull request.

**Comment by wolfboys** [comment]
> @wolfboys I would like to review this pull request. BTW, @GOODBOY008, could you squash the commits into one commit or split this pull request to multi pull requests? IMO, you could introduce the interfaces in this pull request.

welcome to review this pr

**Comment by GOODBOY008** [comment]
@wolfboys @SteNicholas This pr only for sql gateway base module. Please review this pr, If you are available.Thank you~

**Comment by wolfboys** [comment]
@SteNicholas can you review it first? thx 🤗

**Review by wolfboys — APPROVED** [review]
LGTM. Thanks very much for your contribution

**Pull request merged**
