### PR TITLE
[Feature] Add probes for liveness check.

### PR DESCRIPTION
**Pull request by lvshaokang**
## What changes were proposed in this pull request

Issue Number: close #xxx 

Add  probes for liveness checking and better adaptation to k8s deployment[1].

1.https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): yes

### CODE REVIEW

**Comment by lvshaokang** [comment]
cc @MonsterChenzhuo @wolfboys

**Comment by MonsterChenzhuo** [comment]
@lvshaokang I'm not sure if this version will be merged, because this is a feature, and it is planned not to add any new features in November.

**Comment by lvshaokang** [comment]
@MonsterChenzhuo I understand your concern, or this is an enhancement, not a new feature, it better adapt the streampark service for deployment on k8s. Shall we cut this in current verision?

**Comment by wolfboys** [comment]
Thanks for your contribution, I will review it later

**Comment by wolfboys** [comment]
It looks good, can you provide relevant documentation?

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
