### PR TITLE
[improve] job submission parameter optimization

### PR DESCRIPTION
**Pull request by wolfboys**
[improve] job submission parameter optimization

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

How it Works:

### CODE REVIEW

**Comment by wolfboys** [comment]
@Al-assad  @czy006 PTAL

**Review by Al-assad — COMMENTED** [review]
@wolfboys  I think the set method signature should not be the same as the original flink Configuration#set, because there is a possibility that the caller forgets to import the implicit class and uses the native flink configuration method actually.

**Comment by wolfboys** [comment]
> @wolfboys I think the set method signature should not be the same as the original flink Configuration#set, because there is a possibility that the caller forgets to import the implicit class and uses the native flink configuration method actually.

safeSet implicit method ?

**Review by Al-assad — APPROVED** [review]
@wolfboys I'm pretty sorry I misread the method signature of config set🥲 , LGTM.

**Comment by wolfboys** [comment]
> @wolfboys I'm pretty sorry I misread the method signature of config set🥲 , LGTM.

😄

**Pull request merged**
