### PR TITLE
[bug] [fix] [streampark-flink-shims-base] Repair multiple dialect set statement have no effect error.

### PR DESCRIPTION
**Pull request by ziqiang-wang**
Repair multiple dialect set statement have no effect error.

Cause：The sql statement sorts the results at the end of the parseSQL function, disrupting the original order of statements filled by the user, so that all set statements are moved to the beginning and the middle set statement is not executed in its original position.

### CODE REVIEW

**Comment by lvshaokang** [comment]
Hi, @ziqiang-wang. Thanks for you feedback.
Please follow the PR template to describe the changes contributed by the pull request.

**Comment by ziqiang-wang** [comment]
## change
Issue Number: close #1702 

Repair multiple dialect set statement have no effect error.

Cause：
The sql statement sorts the results at the end of the parseSQL function, disrupting the original order of statements filled by the user, so that all set statements are moved to the beginning and the middle set statement is not executed in its original position.

image


## Verifying this change

Only test in idea debug, also need to test the product environment.


Dependencies : no

**Comment by ziqiang-wang** [comment]
## What changes were proposed in this pull request
Issue Number: close #1702

Repair multiple dialect set statement have no effect error.

Cause：
The sql statement sorts the results at the end of the parseSQL function, disrupting the original order of statements filled by the user, so that all set statements are moved to the beginning and the middle set statement is not executed in its original position.

image

## Brief change log


## Verifying this change
Only test in idea debug, also need to test the product environment.

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): no

**Comment by wolfboys** [comment]
Thanks for your contribution, There are still bugs in the actual test. keep going

**Comment by ziqiang-wang** [comment]
Fix the problem that resources of the flink job manager role are not automatically released after the flink sql batch task is successfully run in yarn per job mode.

**Comment by ziqiang-wang** [comment]
The latest pr submission:

1. Fixed an issue where hive sql could not be run due to the platform changing the flink sql order, which could not load hive dialect correctly.
2. Fix the problem that resources of the flink job manager role are not automatically released after the flink sql batch task is successfully run in yarn per job mode.
3. Remove the validity check for keys in the set statement, because the platform is not yet able to aggregate all keys

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
