### PR TITLE
Fix remote task submission could not find the jar

### PR DESCRIPTION
**Pull request by ChengJie1053**
Fix remote task submission could not find the jar

### CODE REVIEW

**Comment by wolfboys** [comment]
Thanks very much for your contribution. Before submitting a pull request, here should be have issue description or email discussion. Please explain the background of the issue clearly, so that the reviewer reviewing the pull request has enough information to better progress the work.

**Comment by ChengJie1053** [comment]
> Thanks very much for your contribution. Before submitting a pull request, here should be have issue description or email discussion. Please explain the background of the issue clearly, so that the reviewer reviewing the pull request has enough information to better progress the work.

Ok, thank you

**Comment by ChengJie1053** [comment]
This pr is used to fix the error that the jar cannot be found when a user submits a remote task

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
