### PR TITLE
[Bug] docker build streampark cannot find flinkhome path

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
## What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

## What is changed and how it works?

Proposal: [xxx](url) 

Feel free to ping committers for the review!

## Contribution Checklist

  - Make sure that the pull request corresponds to a [GITHUB issue](https://github.com/apache/streampark/issues).

  - Name the pull request in the form "[Feature] [component] Title of the pull request", where *Feature* can be replaced by `Hotfix`, `Bug`, etc.

  - Minor fixes should be named following this pattern: `[hotfix] [docs] Fix typo in README.md doc`.

### CODE REVIEW

**Comment by wolfboys** [comment]
Docker-related pr needs to be fully test

**Comment by xinzhuxiansheng** [comment]
@MonsterChenzhuo  Thank you for your contribution. I will review it later

**Comment by xinzhuxiansheng** [comment]
@MonsterChenzhuo   At present, there are some problems when docker-compose deploys the streampark service.
 For example, the path of mysql's final.sql has changed. Can you optimize it together ?

**Comment by wolfboys** [comment]
@MonsterChenzhuo sql ddl has  changed, see: https://github.com/apache/incubator-streampark/pull/1696

**Pull request closed without merging**
