### PR TITLE
[Feature] User can use different hadoop-user to submit application

### LINKED ISSUE #3222: [Feature] when submit application to yarn , use the user logged in to streampark.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.1

### Flink Version

flink-1.17

### deploy mode

yarn-application

### What happened

when submit jar type application to yarn , the user is hadoop-user-name configed in application.yml 
can this use streampark logged in user , or maybe the streampark user could map to a system user?

### Error Exception

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lordk911**
## What changes were proposed in this pull request

Issue Number: close #3222

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): no

### CODE REVIEW

**Comment by wolfboys** [comment]
Overall, it looks good 👍 Keep up the good work! I'm really looking forward to seeing the next update. 😊

**Comment by lordk911** [comment]
@wolfboys I think the key changes are in YarnApplicationClient class, setConfig method directly using UserGroupInformation.setLoginUser method is not correct, should use ProxyUser, This requires either changing the doSubmit method declaration or moving the setConfig changes into the doSubmit method. And config the hadoop-user's keytab on the job definition page is required in a Kerberos-enabled environment too.

**Comment by lordk911** [comment]
> I think the key changes are in YarnApplicationClient class, setConfig method directly using UserGroupInformation.setLoginUser method is not correct, should use ProxyUser, This requires either changing the doSubmit method declaration or moving the setConfig changes into the doSubmit method. And config the hadoop-user's keytab on the job definition page is required in a Kerberos-enabled environment too.

@wolfboys Do you have any suggestions for this? 
1、if use UserGroupInformation.setLoginUser ，The CurrentUser of the other tenant is changed.
2、if use ProxyUser , the user configed as `streampark.hadoop-user-name` should have the ability to represent other users.
3、if kerberos is enabled, each tenant needs to upload their own keytab, and the keytab needs to be protected

**Comment by wolfboys** [comment]
> > I think the key changes are in YarnApplicationClient class, setConfig method directly using UserGroupInformation.setLoginUser method is not correct, should use ProxyUser, This requires either changing the doSubmit method declaration or moving the setConfig changes into the doSubmit method. And config the hadoop-user's keytab on the job definition page is required in a Kerberos-enabled environment too.
> 
> @wolfboys Do you have any suggestions for this? 1、if use UserGroupInformation.setLoginUser ，The CurrentUser of the other tenant is changed. 2、if use ProxyUser , the user configed as `streampark.hadoop-user-name` should have the ability to represent other users. 3、if kerberos is enabled, each tenant needs to upload their own keytab, and the keytab needs to be protected


If Kerberos is involved, things will become complicated. How to manage the Kerberos configurations for different users is a problem we have to face. I suggest not considering Kerberos for now.

**Comment by lordk911** [comment]
@wolfboys The code has been modified to use proxyuser

**Comment by wolfboys** [comment]
> @wolfboys The code has been modified to use proxyuser

Thanks for your contribution, I will review it later

**Comment by caicancai** [comment]
You can modify your title, for example [Feature] User can use different hadoop-user to submit application, the first letter is preferably capitalized, thank you

**Comment by wolfboys** [comment]
The hadoopUser also needs to be set in the application copy method

**Comment by wolfboys** [comment]
One more question, have you tested it? Will the set hadoopUser work ok?

**Comment by lordk911** [comment]
> One more question, have you tested it? Will the set hadoopUser work ok?

I've tested it against streampark 2.1.2

**Comment by lordk911** [comment]
> The hadoopUser also needs to be set in the application copy method

done

**Review by wolfboys — APPROVED** [review]
LGTM, good job🤗

**Pull request merged**
