### PR TITLE
[ISSUE-3330][Feature]add taskmanager.memory.network to TM Memory Options

### PR DESCRIPTION
**Pull request by didiaode18**
## What changes were proposed in this pull request

Issue Number: close [ISSUE-3330]

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

### CODE REVIEW

**Comment by wolfboys** [comment]
Thanks for your contribution! 👏 It looks good, but there is a minor issue with the code style that we need to fix it first.
```
cd streampark-console/streampark-console-webapp
pnpm lint:eslint
```

**Comment by didiaode18** [comment]
image
When I ran the pnpm lint:eslint command, I found that the code style error in this line was not caused by the code I merged. I don’t know if my understanding is correct.

**Comment by didiaode18** [comment]
> image When I ran the pnpm lint:eslint command, I found that the code style error in this line was not caused by the code I merged. I don’t know if my understanding is correct.

@wolfboys

**Comment by wolfboys** [comment]
> he code style error in this line was not caused by the code I merged. I don’t know if my understanding is correct.

Oh, thanks for your feedback. I will merge this PR first. Thanks again for your contribution. We are looking forward to your next PR

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
