### PR TITLE
Update version to 2.1.0

### PR DESCRIPTION
**Pull request by wolfboys**
Update version to 2.1.0

### CODE REVIEW

**Comment by wolfboys** [comment]
cc @1996fanrui PTAL, thx

**Review by muchunjin — APPROVED** [review]
LGTM

**Review by 1996fanrui — COMMENTED** [review]
Thanks for your contribution.

`2.1.0-SNAPSHOT` maybe better? WDYT?

**Comment by wolfboys** [comment]
> Thanks for your contribution.
> 
> `2.1.0-SNAPSHOT` maybe better? WDYT?

I've used `-SNAPSHOT` earlier, I did not see `-SNAPSHOT`  better point, can you tell me why it's better?

**Comment by wolfboys** [comment]
> Thanks for your contribution.
> 
> `2.1.0-SNAPSHOT` maybe better? WDYT?

The current branch is `dev`, which is a branch specially used for development, so I think there is no need to add `-SNAPSHOT`

**Pull request merged**
