### PR TITLE
[Bug] StreamPark cannot search for failed status tasks

### PR DESCRIPTION
**Pull request by xujiangfeng001**
## What changes were proposed in this pull request

Issue Number: https://github.com/apache/incubator-streampark/issues/1907

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): no

### CODE REVIEW

**Comment by xujiangfeng001** [comment]
@wolfboys hi,please review the code for me when you have time.

**Review by wolfboys — APPROVED** [review]
LGTM

**Comment by wolfboys** [comment]
@wangsizhu0504 please konw this change

**Comment by wangsizhu0504** [comment]
Ok, I'll make a synchronous change here as well

**Pull request merged**
