### PR TITLE
[Feature] StreamPark Autonomous Health Probing

### PR DESCRIPTION
**Pull request by xujiangfeng001**
## What changes were proposed in this pull request

Issue Number: https://github.com/apache/incubator-streampark/issues/2944

## Brief change log

Design details can be found in: https://docs.google.com/document/d/1a8-fZVSUi2vOl54J8pSO9MXHHjtbikag4MvnUup61vQ/edit?usp=sharing

## Verifying this change

This change is local testing without any test coverage.

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (no)

### CODE REVIEW

**Comment by wolfboys** [comment]
This is a very useful feature👏, There are some conflicts in the code, please rebase the code first. if the PR is ready, feel free to call me for a review. Good luck!

**Comment by xujiangfeng001** [comment]
Hi @wolfboys ，PTAL.

**Comment by wolfboys** [comment]
> Hi @wolfboys ，PTAL.

reviewing

**Review by wolfboys — APPROVED** [review]
LGTM

**Pull request merged**
