### PR TITLE
drop lockutilsTest failed

### PR DESCRIPTION
**Pull request by Mrart**
## What changes were proposed in this pull request

drop lockutilsTest failed

### CODE REVIEW

**Review by caicancai — CHANGES_REQUESTED** [review]
I have never heard of any open source project doing this. Cancelling the test if it fails is unreasonable. You should fix the problem until the test passes. I personally refuse to merge this PR.

**Comment by Mrart** [comment]
> I have never heard of any open source project doing this. Cancelling the test if it fails is unreasonable. You should fix the problem until the test passes. I personally refuse to merge this PR.

This code has not been used in the project for the time being. I tried to fix it, but there is still a problem. Let's add an issue to follow up this ut test.

**Comment by Mrart** [comment]
> I have never heard of any open source project doing this. Cancelling the test if it fails is unreasonable. You should fix the problem until the test passes. I personally refuse to merge this PR.

This ut test now prevents the merging of all our PRS.

**Comment by caicancai** [comment]
> > I have never heard of any open source project doing this. Cancelling the test if it fails is unreasonable. You should fix the problem until the test passes. I personally refuse to merge this PR.
> 
> This code has not been used in the project for the time being. I tried to fix it, but there is still a problem. Let's add an issue to follow up this ut test.

You should fix the test and merge the PR. This is the case for many open source projects.
I even agree not to delete this test and merge this PR, but I don't agree to delete this test directly.
Can you describe what's wrong with this test? Why does the test fail?

**Comment by wolfboys** [comment]
Thanks for your contribution, but the current PR is a duplicate of this [PR](https://github.com/apache/incubator-streampark/pull/4005)

**Comment by wolfboys** [comment]
Thanks for your contribution. The issue has been resolved.

**Pull request closed without merging**
