### PR TITLE
[Fix] generate token bug fixed.

### PR DESCRIPTION
**Pull request by numbernumberone**
Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

Feel free to ping committers for the review!

## Contribution Checklist

  - Make sure that the pull request corresponds to a [GITHUB issue](https://github.com/streamxhub/streamx/issues).

  - Name the pull request in the form "[Feature] [component] Title of the pull request", where *Feature* can be replaced by `Hotfix`, `Bug`, etc.

  - Minor fixes should be named following this pattern: `[hotfix] [docs] Fix typo in README.md doc`.

-->

### CODE REVIEW

**Comment by wolfboys** [comment]
@lizzy-yang PTAL.

**Comment by lizzy-yang** [comment]
pr #1026

**Comment by lizzy-yang** [comment]
> 
This is not a bug. The user password should not be used here. The token is generated according to username, password and expireTime. If the user password is used here, the access token generated by the same user on the browser will be exactly the same, which is not allowed！

**Comment by xianweiY** [comment]
> @lizzy-yang PTAL.

In fact, the authentication of accesstoken has nothing to do with the user password, because it will directly query the database information. The user password here plays a role of salt value.

**Comment by xianweiY** [comment]
> @lizzy-yang PTAL.

So this is not a bug. On the contrary, it is better to take UUID, which can make accesstoken more random

**Pull request closed without merging**
