### PR TITLE
[Bug] should use fromYamlFile function to read conf file in flink 1.15 shims

### PR DESCRIPTION
**Pull request by KyleZhang0536**
https://github.com/streamxhub/streamx/issues/1409

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

Feel free to ping committers for the review!

## Contribution Checklist

  - Make sure that the pull request corresponds to a [GITHUB issue](https://github.com/streamxhub/streamx/issues).

  - Name the pull request in the form "[Feature] [component] Title of the pull request", where *Feature* can be replaced by `Hotfix`, `Bug`, etc.

  - Minor fixes should be named following this pattern: `[hotfix] [docs] Fix typo in README.md doc`.

### CODE REVIEW

**Comment by wolfboys** [comment]
Thank you for your contribution. I'll review it later

**Comment by KyleZhang0536** [comment]
@wolfboys PTAL

**Comment by wolfboys** [comment]
LGTM

**Comment by wolfboys** [comment]
Thanks for your contribution, we are looking forward to your next contribution.👏👏👏👍

**Pull request merged**
